### ISSUE TITLE
Syntax error Illegal character

### ISSUE THREAD

**Issue by vtomole** [owlbarn/owl#100]
This is what I get when I try to install owl. I deleted the repo, re-cloned it, and tried installing again. The error is still there.
`vtomole@vtomole:~/owl$ make oasis
oasis setup
E: Syntax error Illegal character , in file '_oasis' at line 41, char 33
Makefile:11: recipe for target 'oasis' failed
make: *** [oasis] Error 1
`

**Comment by ryanrhymes** [comment]
Hi Victory, is it because of the version of Oasis? I am using 0.4.10, what is the one you are using?

**Comment by vtomole** [comment]
`vtomole@vtomole:~$ opam install oasis.0.4.10
[NOTE] Package oasis is already installed (current version is 0.4.10).

But then I also get this after running the previous command `vtomole@vtomole:~/owl$ oasis version
'0.4.5
`

**Comment by ryanrhymes** [comment]
Interesting, maybe try `opam update` then `opam upgrade oasis`? Does this help?

**Comment by vtomole** [comment]
`vtomole@vtomole:~/owl$ opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org
vtomole@vtomole:~/owl$ opam upgrade oasis
Already up-to-date.
vtomole@vtomole:~/owl$ oasis version
0.4.5
`
No.

**Comment by dbuenzli** [comment]
@vtomole try `opam install oasis.0.4.10` to explicitely ask for `v0.4.10`.

**Comment by dbuenzli** [comment]
@vtomole nevermind I didn't follow the discussion closesly. 

Are you sure to be in the right switch ? Do an `eval $(opam config env)`, what does `opam info oasis` say ?

**Comment by vtomole** [comment]
https://pastebin.com/JbzkBLLv

**Comment by dbuenzli** [comment]
Does `oasis version` still report `4.5.0` after the `eval $(opam config env)` ? If that is the case please report the outputs of: 

```
oasis version 
opam config exec -- oasis version 
echo $PATH
opam config exec -- env
```

**Comment by dbuenzli** [comment]
Also if you are simply trying to install from source [these instructions](https://github.com/ryanrhymes/owl/issues/101) may be easier.

**Comment by vtomole** [comment]
That error is gone now. Now I'm getting "/usr/bin/ld: cannot find -llapacke" When I try to "make install". I already executed `apt-get install liblapack-dev`

**Comment by ryanrhymes** [comment]
What OS are you using? MacOS or Ubuntu? It is better to install OpenBLAS from source: https://github.com/xianyi/OpenBLAS

**Comment by ryanrhymes** [comment]
You probably need to change this line https://github.com/ryanrhymes/owl/blob/844248b4b0e05dc027f1fc884cd4c54531419c40/_oasis#L144 to point to the directly where it is installed.

But if you instal OpenBLAS, it already included LAPACKE so you can actually remove this line https://github.com/ryanrhymes/owl/blob/844248b4b0e05dc027f1fc884cd4c54531419c40/_oasis#L146

**Comment by dbuenzli** [comment]
> CCLib+:         -L/usr/lib

You don't have to change this manually you can simply set the `LIBRARY_PATH` environment variable to the adequate location. E.g. 
```
LIBRARY_PATH=/path/to/lapack-dir opam pin add owl --dev-repo
```

**Comment by vtomole** [comment]
I install OpenBLAS: https://pastebin.com/uxBpFxS0
And changed the CCLib+. Now it's  `CCLib+:         -L/opt/OpenBLAS/lib
                    -L/usr/local/lib/gcc/7
                    -framework Accelerate
                    -lopenblas
                    -lgfortran`

How do I check if OpenBLAS install? I get "Command not found".
