### ISSUE TITLE
Simpler instructions for building master

### ISSUE THREAD

**Issue by dbuenzli** [owlbarn/owl#101]
The instructions [here](https://github.com/ryanrhymes/owl#installation) seem needlessly long winded. You can simply instruct users to: 

```
opam depext owl
opam pin add owl --dev-repo
```

**Comment by mseri** [comment]
This does not seem to install the `owl` binary and script. But it should not hard to fix

**Comment by mseri** [comment]
Also depext is not installing some required dependencies (`liblapacke-dev` and `libopenblas-dev`)

**Comment by dbuenzli** [comment]
> Also depext is not installing some required dependencies (liblapacke-dev and libopenblas-dev on ubuntu)

The the constraints in the opam file of the repo should be updated.

**Comment by mseri** [comment]
Yes. I want to add them for ubuntu, debian and fedora based distribution, I need to prepare some docker environments to check which dependencies are needed

**Comment by ryanrhymes** [comment]
Owl has changed to jbuilder, the building and installation seems fine now on my machine. In case you spot any issues, please let me know or help me to solve it, really appreciate it.

There might be some glitches but all will be solved soon. The documentation will be also be updated accordingly in near future.
