### ISSUE TITLE
plots: more flexible area/fill function?

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#107]
I want to fill a region between two curves--i.e. all points above the lower curve and below the upper curve should be filled.  `area` is not designed for this, I believe; it adds endpoints at y=0 so that `plfill` will close the curve along the x axis.  I don't think Owl has a function that does what I want, but I may be wrong.

Does a "fill between curves function" seem likely to be useful to others?  I could see writing it like `area`, but without the additional y=0 points.  Then it would be the user's responsibility to concatenate their vectors in the right way for `plfill`.

 Or the function could accept, for example, matrices whose rows or columns would be automatically concatenated to form the curves to be filled.  There are variations on ths scheme--passing lists of vectors, for example.  

There may be tricky parts of the problem that I have not thought through yet.

**Comment by ryanrhymes** [comment]
You are right, I don't remember there is such a function in Owl at the moment to allow you to do that. There are several solutions:

- Use `area` to draw one function with colour different from background, then draw another function with the same colour of the back to mask it. You can use `min2` and `max2` to figure out the upper bound and lower bound. 

- Maybe it is about time to introduce transparency `Alpha` into `spec` list? This may also be useful if two functions intersect with each other.

I agree this is a useful function. I think it is worth adding a general solution for this. I will have a look at how other software to do that. But in case you have any material to share or any suggestions, always welcome. 

Maybe point 1 can be extended to a general solution?

**Comment by mars0i** [comment]
Thanks Liang.  I thought about using the background color to mask the unwanted fill.  That would work but seems inelegant as a long-term solution, since `plfill` already has the capability to fill the region between two curves.  I agree that `Alpha` seems like it could be very useful, although I don't think I need it yet fwiw.

`region` below is one attempt at a solution.  It's almost the same as `area`.  All of the changes are in the first several lines.  The additional trick is that if the function is passed matrices with two rows rather than one row, it treats one row as the upper curve, and the other as the lower curve (it doesn't matter which is which).  The function concatenates the two rows, reversing the second one so that `plfill` can treat the extended vectors as defining a polygon to fill.  Or if the matrices passed have only one row, the function will behave like `area`.  (I moved the code that adds the endpoints at *y=0* into a separate function, but it could stay in the main function.)
```ocaml
let _circular_concat x =
  Owl_dense_matrix.D.(concat_horizontal (row x 0) (reverse (row x 1)))

let _add_ends_at_zero x y =
  let xmin, xmax = Owl_stats.minmax x in
  let x = Array.(append (append [|xmin|] x) [|xmax|]) in
  let y = Array.(append (append [|0.|] y) [|0.|]) in
  x, y

let region ?(h=_default_handle) ?(spec=[]) x y =
  let open Plplot in
  let m, _ = Owl_dense_matrix.D.shape y in
  let x, y =
    if m = 1 then x, y (* if upper, lower bound rows, make closed polygon: *)
    else _circular_concat x, _circular_concat y
  in
  let x = Owl_dense_matrix.D.to_array x in
  let y = Owl_dense_matrix.D.to_array y in
  let x, y = if m = 1 then _add_ends_at_zero x y else x, y in
  _adjust_range h x X;
  _adjust_range h y Y;
  (* prepare the closure *)
  let p = h.pages.(h.current_page) in
  let color = _get_rgb spec p.fgcolor in
  let r, g, b = color in
  let line_style = _get_line_style spec 1 in
  let fill_pattern = _get_fill_pattern spec 0 in
  (* drawing function *)
  let f = (fun () ->
    let r', g', b' = plgcol0 1 in
    plscol0 1 r g b;
    plcol0 1;
    pllsty line_style;
    plline x y;
    plpsty fill_pattern;
    plfill x y;
    (* restore original settings *)
    plscol0 1 r' g' b';
    plcol0 1;
    pllsty 1
  )
  in
  (* add closure as a layer *)
  p.plots <- Array.append p.plots [|f|];
  (* add legend item to page *)
  _add_legend_item p BOX line_style color "" color fill_pattern color;
  if not h.holdon then output h
```
I'm not sure whether it's best to combine `area`'s functionality with this new functionality.  One could define a function that accepted two *y* row vectors and two *x* vectors, or maybe just one *x* vector that will serve as the coordinates for both of the *y* vectors.  (However, using a single *x* vector would mean that both curves would have to be defined at the same points.  That doesn't seem necessary.)

Also, it might make more sense to for `_circular_concatenate` to operate on `Array`s.  Then the function wouldn't need two separate `if m = 1` expressions.  A single `if` could call either `_circular_concat` or `_add_ends_at_zero` (or embed both pieces of code in the `if`.  This was just my first attempt.

**Comment by mars0i** [comment]
I think this is my current favorite strategy:
> Maybe it could be abstracted out into a common function, and then `area` and `region` (with two y and two x vectors as arguments) could both prepare the vectors for the common code and call the common function.

That is, leave `area` as it is but move all of the code beginning with `_adjust_range h x X` into a separate helper function that accepts the same arguments as `area`.  `area` then configures the `x` and `y` arrays and passes them to the helper function.  In addition, `region` (I don't know what to call it) would take four vector arguments, `x1`, `x2`, `y1`, `y2` and calls `_circular_concatenate` on them and passes the results to the helper function.  The helper function should also be visible to the user.  That way if the user already has two vectors that define a closed polygon, they can be passed to this function.  Maybe this function should simply be named `fill`, since it does essentially what `plfill` does, but with extra convenience and flexibility.

**Comment by ryanrhymes** [comment]
Marshall, thanks for the detailed comment, very reasonable imo. Here are some of my thoughts as follows:

- I think it is better to have a separate function in this case instead of having too much semantics in one function. In case we have to extend one function in Plot module, it is better to take advantage the `spec` mechanism. If the `spec` mechanism cannot handle, then it makes more sense to introduce another function.

- It is preferable to let one function do one thing so the APIs are easier to learn, so I would avoid exposing helper functions to users. Of course one style is having a lot of small components then more powerful functions can be built by composing these small ones. But I prefer a bit more complete function (by sacrificing a little bit generality) which simplifies user application.

- Regarding `area` function, let's keep as it is now. In case we extend it, let's make it consistent with the one in Matlab, which stacks the curves. Therefore it can also achieve what you want by passing in the difference of two curves. However, as you mentioned, both `y`s need to be defined on the same `x`. The matlab document is here: https://uk.mathworks.com/help/matlab/ref/area.html

- I would love to merge your plot function into master branch and I think it is very nice. But do you think we can perhaps rename it to `draw_polygon` (to be consistent with `draw_rect` and `draw_circle` and etc.)? It is just a suggestion and I am open to discussion.

**Comment by mars0i** [comment]
This all sounds reasonable to me.  I'm happy to make a PR.   Should I simply copy most of the code from `area`, or should I put the common code into a separate non-public function that both area and `draw_polygon` call?

I didn't know about `@||`; that's very useful.  The one thing I want to add, though, is that it's not enough to just concatenate the two curves as in your example.  One of them has to be reversed or the plot will be very weird (unless that's what one wants!).  So I would write your example like this:
```ocaml
let x = Mat.(x1 @|| (reverse x2));;
let y = Mat.(y1 @|| (reverse y2));;
Plot.draw_polygon ~spec x y;;
```
With the `reverse`, it's not as convenient.  As a user, I would define my own function that automatically did that.  That's why I thought it might be worth including such a function in the API.  However, I don't feel strongly about it.

**Comment by mars0i** [comment]
Oh, I had a thought about the name.  `draw_polygon` could suggest that it only draws the outline of the polygon.  I'm not sure what a better alternative is.  `fill_polygon`?  `polygon_area`? `polygonal_area`?
