### ISSUE TITLE
alternative plotting backend: GR

### ISSUE THREAD

**Issue by nilsbecker** [owlbarn/owl#108]
hi, i just wanted to point out the cross-platform GR library which seems pretty full-featured for 2D and 3D, supports interactive graphics, uses opengl and is actively developed. it is complete enough to be used as a drop-in backend for matplotlib. wrappers are available for python and julia.

https://github.com/jheinen/gr

this might be a possible alternative to plplot for owl going forward?

**Comment by hcarty** [comment]
GR looks really nice! I had not heard of it before now. There is a focus on Python in the main documentation from what I've seen so far. Is a complete C API exposed?

**Comment by hcarty** [comment]
It looks like `gr.h` should provide a lot of what's necessary.

**Comment by nilsbecker** [comment]
i think a complete basic C api is available; they supply also julia and swift bindings that use it.

**Comment by ryanrhymes** [comment]
That looks really good, thanks for sharing @nilsbecker , especially for its support on LaTex strings and colour images. It seems more promising to me now to have a competitive integrated numerical platform in OCaml now ;-) I have been looking for a better alternative for Owl's current plotting backend, and I think this can definitely be a good candidate.

> It looks like `gr.h` should provide a lot of what's necessary.
Yes, indeed. @hcarty do you have any plan on this? :)
