### ISSUE TITLE
Owl crash when environment variable HOME is not defined

### ISSUE THREAD

**Issue by rixed** [owlbarn/owl#116]
Owl should probably not crash depending on the environment.
But beyond that, I don't think it is OK to create any subdirs in $HOME by default.
I use owl to do some matrix computation in a program that runs as root in some restricted system
where creating directories here and there is frowned upon.

As I understand it from a quick glance, those directories are needed by the Zoo subsystem, which is an improved toplevel. Maybe this whole Zoo subsystem should not be included in the core lib owl.cm{x}a at all, but only in owl_zoo.cm{x}a?

**Comment by ryanrhymes** [comment]
@rixed Thanks for reporting it, you comments make perfectly sense. Zoo subsystem has already been separated out from core library, but the code trying to make sub directory still remains in the `owl_dataset` module. I will move it into zoo or find a better solution for storing local data asap.
