### ISSUE TITLE
Feature: In-place modification functions

### ISSUE THREAD

**Issue by bluddy** [owlbarn/owl#118]
It's far more efficient to modify arrays in-place than to copy them to new arrays. The convention in many languages/libraries is to postfix with an underscore. Functions like add_, sub_, mult_, etc would be great. They could then be aliased by +=, -=, +=$, *=$ etc.

**Comment by ryanrhymes** [comment]
I think so. I actually tried another design before by introducing  an extra `out` argument into every function so user can choose where to write output, but it makes the API ugly imo, especially `Algodiff` is a functor built on top. Introducing `add_` is another solution same as that used in Julia. The API is cleaner, the downside is we need to double the size of API we need to maintain. 

I guess there is no perfection solution, so I am happy with current suggest.

**Comment by bluddy** [comment]
Not really doubling the size of the API per se, since many functions don't make sense in terms of in-place modification.

Also, having a unit result type for these functions makes the API clearer, I think.
