### ISSUE TITLE
Feature: views

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#119]
It would be useful to have  a collection of view functions that allowed one to work directly with a part of a matrix in the form of a vector or other submatrix without copying the data into a new structure.  (`Owl.Mat.row` already does this for the sake of efficiency.)

**Comment by ryanrhymes** [comment]
This definitely makes sense. I have included `view` in todo list. Is your use case similar to those what you can view numpy's view?

**Comment by mars0i** [comment]
I don't know numpy, but I just meant that if one doesn't need to modify a part of an array but just wants to read it, then it seems more efficient if a copy isn't made.  Right now `row` does that, but `col` copies the data (for good reasons--we've discussed this).  If I want to treat a column of a matrix as a column vector, it has to be copied.  What I'm imagining is that a view-style version of `col`, so I do something like `let v = view_col m 5`, and then Owl would handle the underlying indexing for me:  I would index into `v` with `get v 0 0`, `get v 1 0`, `get v 2 0`, etc.., but what's really happening under the surface is that `get v 0 1`, for example, is translated into something that performs a `get m 5 1`.

**Comment by bluddy** [comment]
Numpy views are quite flexible, allowing for complicated slices and operations over them. It's essentially a one-step lazy evaluation mechanism: while views can potentially be narrowed further and further by taking views of views, as soon as a computation is performed, the underlying tensor is either read or written to.

**Comment by ryanrhymes** [comment]
Let's discuss in this thread: https://github.com/owlbarn/owl/issues/137
