### ISSUE TITLE
Finding main documentation

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#123]
It might be confusing to an Owl newbie that the main documentation comments for basic matrix operations are in the [`Owl_dense_matrix_generic`](http://www.cl.cam.ac.uk/%7Elw525/owl/Owl_dense_matrix_generic/index.html) documentation.  I think I originally learned this by trying different modules in the documentation until I found the right one.  :-)  `Owl_dense_ndarray_generic` is similar.  I don't think there's anything that points to these pages.  Maybe this is partly due to ocamldoc limitations?

We could add a note to the Matrix Manipulation and Basic Data Types tutorials; that might help.  

Would it make sense to add some kind of general pointer in the main README.md under the link to the generated docs, listing the best modules for documentation?

Another idea would be to add something to the top doc comment in some mli files, flagging this module as one that contains documentation for several other modules.  This note would then show up on the documentation [table of contents page](http://www.cl.cam.ac.uk/%7Elw525/owl/).

**Comment by ryanrhymes** [comment]
I totally agree. The reason of dumping all the doc into generic module is to avoid duplicates in S/D/C/Z modules. I think both solutions you suggested work fine. 

Please do feel free to modify the doc in any sensible way that will make it better. All PRs are welcome to improve the documentation. Also all the tutorials are open wiki so anyone can edit without even PR. 

FYI, if you want to build up-to-date doc locally, go to owl/doc folder and run `make`. It will build a local doc and open browser automatically, very handy. But you need to `opam install odig odoc` first.

**Comment by ryanrhymes** [comment]
Actually, if you have a local copy, in future you want to browse the doc, you can just run `odig doc owl`, credits go to @dbuenzli for the great tool 👍

**Comment by mars0i** [comment]
Great.  I'll go ahead and make some changes to the doc comments and wiki pages when I get a chance.  I wanted to see what you thought of the policies, first.  Thanks.

**Comment by UnixJunkie** [comment]
It would be nice to have the ocamldoc hosted somewhere on the web, and directing people to it through the README.md file of the project...

**Comment by mseri** [comment]
It is here: https://ocaml.xyz/package/index.html
AddIng a direct link to this and to the tutorial book in the README, next to the link to ocaml.xyz,sounds like a good idea. Could you send a PR for that?
