### ISSUE TITLE
sum_cols, sum_rows are slow?

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#125]
This is related to #124, which is arguably unimportant, but this one  might be significant.

`Mat.sum_cols` and `Mat.sum_rows` seem a lot slower than `Mat.sum`.  These are bytecode times, but I investigated because I was suprised at what happened in native code when I shifted from repeatedly calling `sum`, to using `sum_cols`.  Still trying to understand my timings.  I ran the first set of tests below with `sum_rows` as well, and got similar times.  (My crude `time1` function is defined below.)

Running each test twice:
```ocaml
 let m = Owl.Mat.uniform 1 500000000;;
val m : Owl.Mat.mat =

         C0       C1       C2       C3       C4     C499999995 C499999996 C499999997 C499999998 C499999999
R0 0.940058 0.620377 0.127419 0.756517 0.554394 ...   0.177561   0.451027   0.496034  0.0138471   0.339927

# Utils.Genl.time1 Owl.Mat.sum m;;
cpu: 0.320055s, wall: 0.320193s
- : float = 249996677.135371417
# Utils.Genl.time1 Owl.Mat.sum m;;
cpu: 0.325267s, wall: 0.325536s
- : float = 249996677.135371417
# Utils.Genl.time1 Owl.Mat.sum_cols m;;
cpu: 2.473814s, wall: 2.474378s
- : Owl.Mat.mat =
            C0
R0 2.49997E+08

# Utils.Genl.time1 Owl.Mat.sum_cols m;;
cpu: 2.488312s, wall: 2.489074s
- : Owl.Mat.mat =
            C0
R0 2.49997E+08
```

Comparing row sums using `map` and `sum` rather than `sum_cols`, the `gettimeofday` wall times are consistently the same, but the `Sys.time` times are consistently different.  Not sure how to interpret that.  (Wrapping the `map sum` in `of_array` doesn't noticeably change the time.)
```ocaml
# let m = Owl.Mat.uniform 10000 10000;;
val m : Owl.Mat.mat = ...

# let cpu_time, wall_time = Sys.time(), Unix.gettimeofday() in 
   let result = Owl.Mat.(of_array (map_rows sum m) 10000 1) in
   Printf.printf "cpu: %fs, wall: %fs\n%!"
               (Sys.time() -. cpu_time) (Unix.gettimeofday() -. wall_time);
   result;;
cpu: 0.074554s, wall: 0.074557s
- : Owl.Mat.mat =

           C0
   R0 5002.59
   R1 4952.44
   R2 4969.15
   R3 4977.81
   R4 5056.18
          ...
R9995 5005.54
R9996 5014.34
R9997 4979.17
R9998 4942.21
R9999 5004.69

# Utils.Genl.time1 Owl.Mat.sum_cols m;;
cpu: 0.522337s, wall: 0.073119s
- : Owl.Mat.mat =

           C0
   R0 5002.59
   R1 4952.44
   R2 4969.15
   R3 4977.81
   R4 5056.18
          ...
R9995 5005.54
R9996 5014.34
R9997 4979.17
R9998 4942.21
R9999 5004.69
```

This is the definition of `time1`:
```ocaml
let time1 f x =
    let cpu_time, wall_time = Sys.time(), Unix.gettimeofday() in
    let result = f x in
    Printf.printf "cpu: %fs, wall: %fs\n%!" (Sys.time() -. cpu_time) (Unix.gettimeofday() -. wall_time);
    result
```

**Comment by ryanrhymes** [comment]
Hi Marshall, as I answered in https://github.com/ryanrhymes/owl/issues/124, the reason is `sum_row` and `sum_col` use matrix multiplication provided in CBLAS, whereas for simple `sum`, the whole matrix is flattened then uses a simple `for` loop to add the element up.

Based on your feedback, I am leaning to replace `sum_rows` and `sum_cols` with owl's native implementation, to avoid this kind of issues and also to have consistent return and performance. The new implementation has a lot of optimisation to achieve good performance https://github.com/ryanrhymes/owl/blob/ef56c630f9485fac5eb551abb4e539725d91b867/src/owl/owl_dense_common_vec_fold.c#L230

**Comment by mars0i** [comment]
That sounds good.  (It's fascinating to me that an OCaml `for` loop is faster than CBLAS.)

**Comment by bluddy** [comment]
@mars0i CBLAS is much faster than Ocaml for loops. @ryanrhymes was talking about writing a loop in C, which becomes vectorized. The problem was that he was using matrix multiplication to add up a row or column. This involves many extra operations and possibly creating 2 vectors.

**Comment by mars0i** [comment]
Ah, thanks @bluddy.  That makes sense.
