### ISSUE TITLE
Error loading eigen shared library (and one possible solution)

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#129]
The recent [update](https://github.com/ryanrhymes/eigen/commit/e5d388d45412d3f334ad9e5ae99abb5ca729d325) of eigen library can considerably increase its speed. However, one error on my machine was that, after a successful compilation and installation, `utop` shows error messages as follows when trying to load the library:
```
Cannot load required shared library dlleigen_stubs.
Reason: /root/.opam/4.04.0/lib/stublibs/dlleigen_stubs.so: /root/.opam/4.04.0/lib/stublibs/dlleigen_stubs.so: undefined symbol: c_eigen_dsmat_s_data.
File "/root/.ocamlinit", line 1:
Error: Reference to undefined global `Eigen_tensor_s'
```

It might be related to the `-flto` compile option, because during the compilation of eigen, `ar` complains that `plugin needed to handle lto object`.

One workaround I find effective is to change "ar" to "gcc-ar" in [lib/Makefile](https://github.com/ryanrhymes/eigen/blob/master/lib/Makefile). A related post is [here](https://www.reddit.com/r/Gentoo/comments/6b1dlc/plugin_needed_to_handle_lto_object_and_correct/).

**Comment by ryanrhymes** [comment]
@jzstark many thanks for reporting this, this also causes docker image fail to build. I will fix it soon.
