### ISSUE TITLE
Add better serialization methods

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#135]
The current `save` and `load` functions are built on the `Marshal` module.  This makes them very flexible--they can handle structures other than pure Owl data--but they are fragile.  Data might not be readable with a different version of OCaml or a library.

There has been discussion of adding Owl-specific [HDF5](https://opam.ocaml.org/packages/hdf5/) wrappers, or using `Bigarray.Genarray.map_file` to write an ndarray into a block of binary data that can be written to and read from disk.

The `map_file` method might be easier to implement and should be efficient.  The HDF5 method might require a little bit more work(?), and could be less inefficient, but should also allow interchange with other software such as Python, Matlab, R, etc.

OPAM also has binary data serialization libraries [biniou](https://opam.ocaml.org/packages/biniou/) and [msgpck](https://opam.ocaml.org/packages/msgpck/), but HDF5 is probably better because it's a cross-platform standard.  JSON would be cross-platform but is probably not a good idea because it's not very compact.

(Most of these points come from discussion in the slack channel on 12/4/2017-12/6/2017.)

Owl also has `save_txt` and `load_txt` which write and read CSV files.

**Comment by nilsbecker** [comment]
also relevant, this thread: 

https://discuss.ocaml.org/t/ocaml-vega-lite-and-ocaml-dataframes/1075

in particular, apache arrow and xarray mentioned there.
