### ISSUE TITLE
Proposal for root finding algorithms

### ISSUE THREAD

**Issue by kanisteri** [owlbarn/owl#177]
Root finding algorithms are quite fundamental in numerical libraries. There seems none in Owl at the moment. I notice you included some incomplete C functions in the repo but not interfaced yet. Given you currently have a `Base` lib for pure OCaml implementation, I propose to include the pure OCaml implementation of basic root finding algorithms.

If you think this proposal makes sense. I can use my spare time to write up some such functions for Owl.

**Comment by ryanrhymes** [comment]
@kanisteri It sounds terrific to me! Root finding has been on my TODO but I probably will never have enough time to implement them myself. Glad you can work on this, many thanks!

So go for it 🥇 👍

**Comment by mseri** [comment]
This would be great to have. It would allow us to implement all the implicit solvers we had to postpone in owl ode

**Comment by ryanrhymes** [comment]
@mseri http://ocaml.xyz/apidoc/owl_maths_root.html

**Comment by mseri** [comment]
I knew about these, but they are only one dimensional. We need vector valued functions
