### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by cpitclaudel** [owlbarn/owl#186]
Hi there,

I'm running issues trying to install owl.  I started with a simple `opam install owl`, which failed repeatedly until I figured out which external dependencies I needed.  Was there a good way to list them? I ended up needing `apt install liblapacke-dev libgsl-dev libshp-dev`, but there was a lot of trial and error involved.

I got this message when I `#require "owl"`:

    # #require "owl";;
    /home/clement/.opam/4.06.0/lib/ocaml/unix.cma: loaded
    /home/clement/.opam/4.06.0/lib/ocaml/bigarray.cma: loaded
    /home/clement/.opam/4.06.0/lib/bytes: added to search path
    /home/clement/.opam/4.06.0/lib/integers: added to search path
    /home/clement/.opam/4.06.0/lib/integers/integers.cma: loaded
    /home/clement/.opam/4.06.0/lib/integers/integer_printers.cma: loaded
    /home/clement/.opam/4.06.0/lib/ctypes: added to search path
    /home/clement/.opam/4.06.0/lib/ctypes/ctypes.cma: loaded
    /home/clement/.opam/4.06.0/lib/ctypes/ctypes-top.cma: loaded
    /home/clement/.opam/4.06.0/lib/ocaml/str.cma: loaded
    /home/clement/.opam/4.06.0/lib/ctypes/cstubs.cma: loaded
    /home/clement/.opam/4.06.0/lib/dolog: added to search path
    /home/clement/.opam/4.06.0/lib/dolog/dolog.cma: loaded
    /home/clement/.opam/4.06.0/lib/eigen: added to search path
    /home/clement/.opam/4.06.0/lib/eigen/eigen.cma: loaded
    /home/clement/.opam/4.06.0/lib/gsl: added to search path
    /home/clement/.opam/4.06.0/lib/gsl/gsl.cma: loaded
    Cannot load required shared library dllgsl_stubs.
    Reason: /home/clement/.opam/4.06.0/lib/stublibs/dllgsl_stubs.so: /home/clement/.opam/4.06.0/lib/stublibs/dllgsl_stubs.so: undefined symbol: gsl_ran_multivariate_gaussian.
    /home/clement/.opam/4.06.0/lib/plplot: added to search path
    /home/clement/.opam/4.06.0/lib/plplot/plplot.cma: loaded
    /home/clement/.opam/4.06.0/lib/owl: added to search path
    /home/clement/.opam/4.06.0/lib/owl/owl.cma: loaded
    Cannot load required shared library dllowl_stubs.
    Reason: /home/clement/.opam/4.06.0/lib/stublibs/dllowl_stubs.so: /home/clement/.opam/4.06.0/lib/stublibs/dllowl_stubs.so: undefined symbol: LAPACKE_dsygst.

… but things still seemed to work, so I tried to `#require "owl_top"`.  This failed with `No such package: owl_top`.  I presumed that was because I wasn't on master (but a link to the appropriate docs on the master README would be nice), so I tried to install the dev version:

```
$ opam pin add owl --dev-repo
owl is now git-pinned to git+https://github.com/ryanrhymes/owl.git

[ERROR] Command "git fetch -q origin" failed:
# opam-version 1.2.2
# os           linux
# command      git fetch -q origin
# path         /home/clement/.opam/4.06.0/packages.dev/owl
# exit-code    128
# env-file     /home/clement/.opam/log/log-16305-05296d.env
# stdout-file  /home/clement/.opam/log/log-16305-05296d.out
# stderr-file  /home/clement/.opam/log/log-16305-05296d.err
### stderr ###
# fatal: Unable to find remote helper for 'git+https'
```

I changed to this, which failed too:

```
$ opam pin add owl https://github.com/ryanrhymes/owl.git
[NOTE] owl is currently git-pinned to git+https://github.com/ryanrhymes/owl.git.
Proceed ? [Y/n] y
owl is now git-pinned to https://github.com/ryanrhymes/owl.git


[owl] https://github.com/ryanrhymes/owl.git updated
[owl] Installing new package description from https://github.com/ryanrhymes/owl.git

owl needs to be reinstalled.
The following actions will be performed:
  ↗  upgrade owl 0.3.0 to dev*
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing  1/1: [owl: git]
[owl] https://github.com/ryanrhymes/owl.git already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   owl.0.3.0
[ERROR] The compilation of owl failed at "jbuilder build -p owl -j 4".

#=== ERROR while installing owl.dev ===========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p owl -j 4
# path         /home/clement/.opam/4.06.0/build/owl.dev
# compiler     4.06.0
# exit-code    1
# env-file     /home/clement/.opam/4.06.0/build/owl.dev/owl-16358-a71bb4.env
# stdout-file  /home/clement/.opam/4.06.0/build/owl.dev/owl-16358-a71bb4.out
# stderr-file  /home/clement/.opam/4.06.0/build/owl.dev/owl-16358-a71bb4.err
### stderr ###
# Error: Library "owl_base" not found.
# -> required by library "owl" in _build/default/src/owl
# -> required by META.owl
# Hint: try: jbuilder external-lib-deps --missing -p owl @install
# File "src/owl/jbuild", line 23, characters 9-3261:
# Error: Library "owl_base" not found.
# -> required by library "owl" in _build/default/src/owl
# Hint: try: jbuilder external-lib-deps --missing -p owl @install
```

I tried the hints:

```
$ jbuilder external-lib-deps --missing -p owl @install
Error: I don't know about package owl (passed through --only-packages/--release)
```

Not sure what to try next :/ Can you help?

Thanks!

**Comment by jzstark** [comment]
I had similar problem in #104 about the error `undefined symbol: LAPACKE_dsygst`. I think that could be solved by adding a line of `-llapacke` after "-lgfortran" in the `src/owl/jbuild` file. 

Also, I think the [Dockerfile](https://github.com/ryanrhymes/owl/blob/master/docker/Dockerfile.ubuntu) might be helpful in clarifying some issues such as external dependencies.

**Comment by onionhoney** [comment]
Hi there. I had a similar series of failed attempts and here are my steps. 

First, for the 'git+https' remote helper not found issue, installing opam 2.0.0~rc solved it for me.

Next, I was able to resolve 'owl_base not found' by pinning owl_base as a new package with `opam pin add owl_base git+https://github.com/ryanrhymes/owl.git`, before running `opam pin add owl --dev-repo`.

**Comment by vd1** [comment]
@onionhoney many thanks! it worked swimmingly.

**Comment by Ejhfast** [comment]
I'm seeing a similar issue using opam version 2.1.0 and owl/owl-base version 1.0.1:

```
utop # #require "owl-top";;
No such package: owl-top
```

Or when I try just owl:

```
utop # #require "owl";;
Cannot load required shared library dllowl_stubs.
Reason: /home/fast/.opam/system/lib/stublibs/dllowl_stubs.so: /home/fast/.opam/system/lib/stublibs/dllowl_stubs.so: undefined symbol: LAPACKE_dlagge.
```

Are there any known issues or workarounds? Perhaps the [guide](https://ocaml.xyz/book/introduction.html) should be updated?

**Comment by bluddy** [comment]
This is a known issue with the openblas included in Ubuntu.
See [this](https://discuss.ocaml.org/t/owl-undefined-symbols-after-standard-installation/4186/12).

**Comment by Ejhfast** [comment]
Thanks! I was able to get it to work by uninstalling `owl`, installing openblas manually, and then reinstalling `conf-openblas` before `owl`. Something else that's missing from the guide is that you need to install `owl-top` independently of owl. I don't know enough about owl or opam to say whether this is due to bugs in the default approach to installation or whether the guide should be updated.
