### ISSUE TITLE
adding `gemm_diag`

### ISSUE THREAD

**Issue by ghennequin** [owlbarn/owl#190]
Just following up on our slack conversation: would it be possible to add "`gemm_diag`"?
Intended behaviour:

`gemm_diag a b` → `Mat.(a *@ b |> diag)`. Thanks!

**Comment by ryanrhymes** [comment]
Can this be solved by the following code?

```ocaml
Mat.(sum ~axis:0 (y * (transpose x)));;
```

The complexity of multiplication is `O(N^2)`, but transpose may introduce some overhead. Depends on the size of the matrix, it should still be faster than `Mat.(x *@ y |> diag` imo.

**Comment by ghennequin** [comment]
Yes, this works; clever!
