### ISSUE TITLE
Complex scalars for Algodiff

### ISSUE THREAD

**Issue by igarnier** [owlbarn/owl#201]
It would be nice to have support for complex scalars in the Algodiff module.
This would require the addition of a `Owl_maths_complex` module first.

**Comment by ryanrhymes** [comment]
A new `owl_base_complex` module has been added to support complex number maths. Unit tests only has place holder so not fully tested, use with care.

Check the ref: http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_base_complex.html
