### ISSUE TITLE
opam install fails without helpful error

### ISSUE THREAD

**Issue by nilsbecker** [owlbarn/owl#213]
i just tried installing owl from opam repository. mac os x 10.12.6. 

i get this output:

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of owl failed at "jbuilder build -p owl -j 4".

#=== ERROR while installing owl.0.3.0 =========================================#
# opam-version 1.2.2
# os           darwin
# command      jbuilder build -p owl -j 4
# path         /Users/nbecker/.opam/4.06.1+flambda/build/owl.0.3.0
# compiler     4.06.1+flambda
# exit-code    1
# env-file     /Users/nbecker/.opam/4.06.1+flambda/build/owl.0.3.0/owl-45700-1872ec.env
# stdout-file  /Users/nbecker/.opam/4.06.1+flambda/build/owl.0.3.0/owl-45700-1872ec.out
# stderr-file  /Users/nbecker/.opam/4.06.1+flambda/build/owl.0.3.0/owl-45700-1872ec.err
### stderr ###
# [...]
# Warning 3: deprecated: Bigarray.Genarray.map_file
# Use Unix.map_file instead.
# Note that Bigarray.Genarray.map_file raises Sys_error while
# Unix.map_file raises Unix_error.
#     ocamlopt src/owl/.owl.objs/owl_dense_ndarray_z.{cmx,o}
# File "src/owl/owl_dense_ndarray_z.ml", line 46, characters 31-48:
# Warning 3: deprecated: Bigarray.Genarray.map_file
# Use Unix.map_file instead.
# Note that Bigarray.Genarray.map_file raises Sys_error while
# Unix.map_file raises Unix_error.
```
the .out file shows nothin, the .err file shows what's shown here.

**Comment by mor1** [comment]
I think that's because 4.06 errors out on warnings by default. I did some work on the OPAM packaging yesterday, now merged. Once the `conf-openblas` update gets merged to opam-repository, @ryanrhymes should be able to issue a new release which ought to install more reliably from OPAM.

**Comment by nilsbecker** [comment]
oh really? i didn't know that warnings are fatal now. that seems quite a rigorous change. (but i'm not against it)

**Comment by mor1** [comment]
it's either that or the jbuild runes turn it on...
Until we get a new release out, it's probably best to build directly from source for now. `make install` in the cloned `owlbarn/owl` repo should work I think.

**Comment by nilsbecker** [comment]
not for me unfortunately. i'll comment in the local install issue.

**Comment by ryanrhymes** [comment]
@nilsbecker is your local clone up-to-date? Can you try to sync with master branch? I remember I fixed this `map_file`
 issue some time ago.

**Comment by ryanrhymes** [comment]
My apologies, now I see, you are installing from OPAM. V.0.3.0 is way too outdated. We will try to publish a new release soon.

**Comment by mor1** [comment]
0.3.7 is going through OPAM CI checking now. Hopefully I'll be able to get it through tonight, so will close this for now.
