### ISSUE TITLE
Travis failed in owl

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#227]
I notice that after commit [9b9ad](https://github.com/owlbarn/owl/commit/9b9ad77b5fd01f7a714f30018e89b056396e1d51) Travis fails with message:
```
# File "src/owl/dense/owl_dense_ndarray_generic.ml", line 3604, characters 11-34:
# Error: Unbound value Owl_utils.Array.replace
```
Once I copy this replace function into `owl_dense_ndarray_generic.ml` and call it instead of Owl_utils.Array.replace, the Travis test is successful again. 

On the other hand, its [previous commit](https://github.com/owlbarn/owl/commit/db6e0868049451a41c82074c1de3e26c5b5c7da2) passes Travis successfully.  So I'm confused about what may have caused this issue, since the code involved doesn't seems to related to the `Owl_utils` module. Any help would be greatly appreciated. Thanks!  @mor1

**Comment by mor1** [comment]
Don't know off top of my head. I'm going to try to push on and get the `conf-openblas` and `owl` OPAM PRs through today/tomorrow. I'll take a look again at the Travis and Docker setups in the Owl repo then.
