### ISSUE TITLE
Automatic build of docker images fails

### ISSUE THREAD

**Issue by ryanrhymes** [owlbarn/owl#229]
Currently, most automatic docker image builds fail. See https://hub.docker.com/r/owlbarn/owl/builds/

The reason is due to the `-llapacke` linking option. This linking option only make senses on Ubuntu because the binary installation of OpenBLAS on Ubuntu does not include Lapacke so we have to install lapacke seprately. 

However, for other Linux distributions, separate Lapacke is not needed since OpenBLAS binary already includes all the functions. `-llapacke` linking option then will cause linking error on non-ubuntu systems.

**Comment by gaborigloi** [comment]
I ran into a similar issue when compiling owl with the latest openblas built from source.
I got an error `/usr/bin/ld: cannot find -llapacke`.
I had to remove `-llapacke` from `configure.ml` to make it work:
```diff
diff --git a/src/owl/config/configure.ml b/src/owl/config/configure.ml
index 5df90be5..6e7f1905 100644
--- a/src/owl/config/configure.ml
+++ b/src/owl/config/configure.ml
@@ -48,7 +48,7 @@ let get_default_libs c =
     "-lm";
   ] in
   get_os_type c |> function
-  | ("linux"|"linux_elf") -> "-llapacke" :: ls
+  | ("linux"|"linux_elf") -> ls
   | (""|"macosx"|"mingw64") -> ls
   | s -> failwith ("get_default_libs: unknown system "^s)
 ```
Maybe configurator could detect whether `-llapacke` is needed by trying to compile some small c programs.

**Comment by ryanrhymes** [comment]
Installation process still needs a lot of work, software configuration and dependency is always a pain on different platforms, especially for complex software like Owl. I was unfortunately overwhelmed by the core development work so cannot really sort this out. 

Help is appreciated.

**Comment by gaborigloi** [comment]
I gave this a go using the method I've described above, and it compiled on my machine - wrote a small c program that prints out the LAPACK version: 
```diff
diff --git a/src/owl/config/configure.ml b/src/owl/config/configure.ml
index 5df90be5..0fe07933 100644
--- a/src/owl/config/configure.ml
+++ b/src/owl/config/configure.ml
@@ -42,13 +42,27 @@ let get_default_cflags _c = [
 ]
 
 
+let openblas_includes_lapacke c =
+  C.c_test c ~link_flags:["-lopenblas"] {|
+#include <lapacke.h>
+#include <stdio.h>
+
+int main(void) {
+  lapack_int vers_major = 0, vers_minor = 0, vers_patch = 0;
+  LAPACK_ilaver(&vers_major, &vers_minor, &vers_patch);
+  printf("LAPACK version: major=%d, minor=%d, patch=%d\n", vers_major, vers_minor, vers_patch);
+  return 0;
+}
+|}
+
 let get_default_libs c =
   let ls = [
     "-lopenblas";
     "-lm";
   ] in
   get_os_type c |> function
-  | ("linux"|"linux_elf") -> "-llapacke" :: ls
+  | ("linux"|"linux_elf") ->
+    if openblas_includes_lapacke c then ls else "-llapacke" :: ls
   | (""|"macosx"|"mingw64") -> ls
   | s -> failwith ("get_default_libs: unknown system "^s)
 
 ```
I'll try to test this a bit more.
