### ISSUE TITLE
Extension to Zoo naming scheme

### ISSUE THREAD

**Issue by ryanrhymes** [owlbarn/owl#231]
@jzstark We had this discussion before about when to refresh local cached Zoo gists. This turns out to be very useful whenever if I need to edit some gists online then try it out immediately on local machine, I always need to run `owl -update gist_id` first.

I think we can extend the current naming scheme in Zoo by adding a field to specify how the gist should be refreshed, e.g. FREQ=Xhour/days/..., ALWAYS ... Then I can write something like

```ocaml
#zoo "6f28d54e69d1a19c1819f52c5b16c1a1/?refresh=always"
```

Does this make sense?

**Comment by jzstark** [comment]
Sure! I think we can actully replace the current "latest" field with this "refresh" field to indicate the time-tolerance of a gist: "gid / refresh". By setting refresh to `0` or `always`, it means always updating the gist regardless of local cache; to `infinity` or `never` (default), it means the current "latest" setting -- always using a local gist whenever possible; and then what sits in between is `Xmins/hrs/days`. I've put this on my TODO.

**Comment by ryanrhymes** [comment]
Good, glad to know it helps to address the ambiguity issue we discussed before. 0 to inf sounds good to me, we can discuss what format to represent time tomorrow.
