### ISSUE TITLE
batch sampling from softmax distribution

### ISSUE THREAD

**Issue by ghennequin** [owlbarn/owl#237]
It would be great to have a function that does batch sampling of the (batch) output of a softmax (i.e. if the output of the softmax is `MxN` where `M` is the number of samples and `N` is the number of output categories, and therefore each row contains the probabilities for a categorical distribution, then we want to return an `MxN` matrix where each row is the one-hot encoding of a sample of the corresponding distribution).

**Comment by mseri** [comment]
@ryanrhymes why did you close this?

**Comment by ryanrhymes** [comment]
oh, missed your comment. I closed some issues which do not seem active and critical. I also consulted jianxin who told me there are no similar APIs in other frameworks. But please do feel free to reopen it if you think this is an important feature.
