### ISSUE TITLE
Freeze neuron's weight in training

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#239]
In constructing a neural network in Tensorflow, user can choose to initialise the weight value as a `tf.varialble` or `tf.const`. The latter means that the weight will not be updated during training. I find this property useful in some use cases, such as neural style transfer. I think it would be great to have such "freeze" mechanism in Owl's NN module.

**Comment by ryanrhymes** [comment]
@jzstark is this still relevant? or implemented already?

**Comment by jzstark** [comment]
Sorry my bad, this function is still not implemented yet.
