### ISSUE TITLE
Tensor compilation?

### ISSUE THREAD

**Issue by bcdarwin** [owlbarn/owl#246]
Recently taking advantage of the underlying language's compiler (or some augmentation thereof) seems to be popular, thanks to recent DLVM (dlvm.org) papers; more recent projects include Swift for Tensorflow and Facebook's Glow.  The frontend DSLs for these projects seem to be inspired by Scala's LMS so should be amenable to implementation in stock Ocaml (pulling in MetaOcaml as a dependency doesn't seem reasonable unfortunately) but implementing the rest of the compilation pipeline might take some thought ...

**Comment by dc-mak** [comment]
I've been working on something compiler-y. I will make the repo public after my deadline on the 1st of June. @ryanrhymes You can take a look at my LT4LA repo and thesis so far to get an idea. I don't think you need full staging - a PPX extension and some dune-hackery can get you pretty far.

**Comment by bluddy** [comment]
@ryanrhymes You may want to check out [ocamlverse.github.io]. It's a comprehensive site for documenting anything ocaml-related, and anyone can get commit access. I'd love to have these scientific computing topics on there, because many people are looking for that.

**Comment by dc-mak** [comment]
Repo is public now: https://github.com/dc-mak/lt4la
Thesis* is here: https://github.com/dc-mak/lt4la/blob/master/write-up/dissertation.pdf, undergoing minor tweaks until final submission on Friday, at which point I'll email you a copy, happy to discuss consent then :)
* I have tried to write this thesis in a fairly accessible manner, so even if you're not an academic, feel free to peruse through it to get a feel of linear types for linear algebra in OCaml
