### ISSUE TITLE
copy_to doesn't check bounds

### ISSUE THREAD

**Issue by dc-mak** [owlbarn/owl#247]
Is this the intended behaviour? Usually there's some assert or runtime check before executing something like this:
```ocaml
let x = Mat.uniform 5 5
let y = Mat.uniform 1 1
Mat.copy_to x y
```
(results in a segfault/core dump for me)

**Comment by ryanrhymes** [comment]
Dhruv, thanks for pointing it out. That is a bug needs to be fixed.

**Comment by jzstark** [comment]
In current implementation, if you execute ` Mat.copy_ x y` the shape checker will work and return an exception:

```
Exception: Owl_exception.DIFFERENT_SIZE: 25 is not equal to 1.
```
