### ISSUE TITLE
Mat.semidef fails Linalg.D.is_symmetric for sizes 61 and greater

### ISSUE THREAD

**Issue by dc-mak** [owlbarn/owl#253]
It may vary by machine? Try a binary search on `n=1`, and doubling until following fails
```ocaml
Linalg.D.is_symmetric @@ Mat.semidef n
```
and doing a binary search. I can reliably have matrices at size 60 pass the above line and then as soon as I hit 61, starts failing.

**Comment by ryanrhymes** [comment]
`Mat.semidef` uses matrix product to generate a semi-definite matrix, so is it because of the float number precision issue? I remember someone reported this before, Matlab and other tools have the exactly the same issue.

**Comment by dc-mak** [comment]
Probably - floating point multiplication can be commutative but not associative, and so for A = (v0 ... vn), A^T = ( (v0^T * v0)    (v0^T * v1)  ... (v0^T * vn) ; (v1^T * v0) ... ; ... ). A(0,1) = v0^T * v1 = v1^T * v0 = A(1,0) mathematically, but they're added in the reverse order. I was more surprised that this showed up reliably for some numbers (61 >, but not as often for n=64 or n=128) than the fact that it happens at all.
Maybe it's worth only doing computing for half the matrix and then copying the rest over?
