### ISSUE TITLE
Dataframe `make` with optional data returns empty dataframe

### ISSUE THREAD

**Issue by xyc0562** [owlbarn/owl#256]
```#require "owl";;
#require "owl-top";;
let open Owl.Dataframe in
let data = [| pack_float_series[| 1.; 2.; 3. |] |] in
make ~data [| "col1" |];;
``` 

Yields:
```- : Owl_dataframe.t =
+----
 col1
```

which indicates an empty dataframe.

This should be caused by
``` 
let used = 0 in
let size = 0 in
{ data; head; used; size }
```

part of the 'make' function.

**Comment by ryanrhymes** [comment]
Yucheng, thank you for reporting this. I have fixed the issue in this commit https://github.com/owlbarn/owl/commit/9f1c4ed5f4413f0c8f7f5ede0b4c9cfbeb702ac2

Dataframe is quite a new module and an initial attempt to introduce more powerful data manipulation functionality into Owl, so there might be more bugs, please do let know if you find out more. Many thanks!
