### ISSUE TITLE
histogram function return values of bins

### ISSUE THREAD

**Issue by tachukao** [owlbarn/owl#262]
Currently,  `Stats.histogram` returns an int array, which is the count in each bin, but does not return the values of the bins. It would be great to allow the users to either
1. specify the values of each bin in a float array passed into the function
2. or infer the values of each bin based on the desired number of bins.

The histogram function would look something like this
``val histogram: float array -> ?bin_vals: float array option -> int  ->  int array * float array``
where `bin_vals` is a float array that contains the bin values and the output is (int array of count in each bin, float array of bin values). 
This would be really helpful! Thanks

**Comment by nilsbecker** [comment]
i would vote for specifying all bin edges and calling them that as well `bin_edges` or something like that. this should make it clear that you need n+1 bin edges to get n bins.

in numpy the histogram function has more bells and whistles. it takes an optional argument that allows a choice of output normalization: 
-  counts
-  fractional counts that sum to 1.
-  bin-density values whose discretized integral over the bins integrates to 1.

i would suggest an api where the histogram itself has the simple type proposed above but there are two convenience functions that take the output tuple and transform it to fractional counts or fractional integrals.

finally, 2-d and n-d histograms would also be great additions

**Comment by nilsbecker** [comment]
one could also consider a small submodule `Histogram` with a type that is a record with the bin and count info, and these convenience functions...

**Comment by nilsbecker** [comment]
i have created a pull request with a preliminary version of a histogram that returns a tuple of bins and counts, and allows specifying (non-uniform) bins

**Comment by ryanrhymes** [comment]
> one could also consider a small submodule `Histogram` with a type that is a record with the bin and count info, and which contains the convenience functions...

The record type sounds like a very good solution to me, just like hypothesis functions in Stats module which returns a record type containing null hypothesis and p-value and score.

**Comment by ryanrhymes** [comment]
Merge PR https://github.com/owlbarn/owl/pull/264
