### ISSUE TITLE
Unittest error in openmp mode

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#274]
One problem I find when I test the newest master branch code is that, when set to openmp mode, two test cases might fail in `unit_lazy.ml` (`fun01` and `fun07`) sometimes.  Here are these two tests:
```ocaml
let fun01 () =
  let x = M.var_arr "" in
  let y = x |> M.sin |> M.cos in
  M.assign_arr x x3;
  M.eval_arr [|y|];
  let a = M.unpack_arr y in
  let b = x3 |> Arr.sin |> Arr.cos in
  Arr.(a = b)

let fun07 () =
  let x = M.var_arr "" in
  let y = M.var_arr "" in
  let z = M.pow x y in
  M.assign_arr x x2;
  M.assign_arr y x3;
  M.eval_arr [|z|];
  let a = M.unpack_arr z in
  let b = Arr.pow x2 x3 in
  Arr.(a = b)
```

It looks weird, since the functions involved in these two cases are the most basic `sin` `cos` and `pow` operations.  I was thinking if anyone is having the same problem or it is just my own machine.

**Comment by ryanrhymes** [comment]
Thanks for reporting this, I will investigate into this issue soon.
