### ISSUE TITLE
Stats_Dist module

### ISSUE THREAD

**Issue by adscib** [owlbarn/owl#279]
I've been looking into a possibility of using Owl for probabilistic programming and I've noticed that the modules in the `ppl` folder define functors that expect a module of type `Stats_Dist`. Unfortunately I was unable to find a module of this type anywhere. Does such a module exist somewhere or can I construct it somehow?

**Comment by ryanrhymes** [comment]
Hi Adam, PPL has been planned but it will not be finished very soon as far as I can tell. I have been implementing various modules needed in a PPL, e.g. [Owl_distribution](https://github.com/owlbarn/owl/blob/master/src/owl/ppl/owl_distribution.mli) is for generating a large amount of random values of given distributions efficiently. However, many pieces are still missing, e.g. the core inference engine is not done yet, and I cannot tell at the moment when it will be implemented.

**Comment by adscib** [comment]
That's fine, I'm happy to write the inference engine myself. All I need is a module of basic distributions which I can can sample from and compute their PDFs in a way compatible with autodiff. It looks like `Owl_distribution` does exactly what I need, I just can't figure out how to construct it, i.e. how to get a module of type `Stats_Dist` to supply to `Owl_distribution.Make`.

**Comment by ryanrhymes** [comment]
Hah, that is great! I'd love to hear any progress on this, am very interested on this topic.

For `Owl_distribution`, you only need to pass in an ndarray module which implements the functions defined in `Stats_Dist` module. E.g. the following code generates a module of double precision.
```ocaml
module M = Owl_distribution.Make (Dense.Ndarray.D);;
```
while this one generates single precision
```ocaml
module M = Owl_distribution.Make (Dense.Ndarray.S);;
```

Generating random numbers is quite straightforward, very much like what you can do in TensorFlow.
```ocaml
module M = Owl_distribution.Make (Dense.Ndarray.D);;
let mu = Arr.of_array [|1.; 3.; 5.|] [|3|];;
let sigma = Arr.of_array [|0.5; 0.7; 0.9|] [|3|];;
let rvs = M.Gaussian.make ~mu ~sigma;;
let samples = M.Gaussian.sample rvs 100;;
```
The code above generates 100 samples for three Gaussian distribution with different parameterisation, i.e. `(mu=1, sigma=0.5)`, `(mu=3, sigma=0.7)`, `(mu=5, sigma=0.9)`. Note that the lowest dimension is for sample, the rest dimensions match your parameter shape.

**Comment by adscib** [comment]
Thanks, that seems to work. I'll try to get the inference running.
