### ISSUE TITLE
OpenBLAS conflicts with OpenMP in Owl

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#283]
Recently I’m looking at using OpenMP in Owl. OpenMP is partly used in the C code of the `core` module to improve performance of e.g. math and convolution operations. Ideally more threads will lead to faster speed. 

However, on my 4-core-CPU Linux laptop it shows the opposite behaviour: when I turn on the openmp switch in Owl and run this test OCaml code:
```ocaml
module N = Dense.Ndarray.S
let _ = 
let n = 1000000 in 
let x = N.ones [|n|] in 
N.sin x
```
the running time of `N.sin x` actually grows with more threads being added in OpenMP. Further experiment shows that only one CPU core is actually utilised regardless of OpenMP thread numbers.  Note that this issue is not universal; it does not exist on MacOS as far as I know. 

After some investigation, I find out that OpenBLAS has a [known issue](https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded) of conflicting with multi-threaded applications. The solution is that, if the application is parallelised by OpenMP, then I need to build OpenBLAS with `USE_OPENMP=1` before installing Owl. 

One question here is whether adding `USE_OPENMP` in compiling OpenBLAS will affect its performance in non-openmp applications. Currently I've conducted some initial evaluations on [basic ndarray operations](https://github.com/owlbarn/owl/blob/master/perftest/perf_dense_ndarray.ml) and convolution operations, and it appears that their running speed is not affected, though more test cases are required to prove that using `USE_OPENMP` is indeed side-effect-free.

Another problem is about the OpenBLAS version. What I've mentioned so far is conducted on the version 0.2.20. In the recently released [0.3.0](https://github.com/xianyi/OpenBLAS/releases), this issue is said to be fixed. To check if I still need to compile OpenBLAS with `USE_OPENMP`,  I've installed 0.3.0 OpenBLAS on my machine and evaluate the running time of `lazy_mnist.ml` and `mnist_cnn.ml` examples. When using `USE_OPENMP`, the result is the same as that of ver. 0.2.20 with `USE_OPENMP` set; however, when it is compiled without `USE_OPENMP` and Owl uses openmp, both examples runs 2-3 times slower (the baseline here is setting Owl to non-openmp mode using version 0.2.20 OpenBLAS without `USE_OPENMP`). This performance degradation is caused by the slower running speed of convolution operation, and is *not* observed on other ndarray operations such as `sin` and `cos` so far. I'm still trying to investigate further but at least we can say it is not always a safe option to switch the OpenBLAS to newer version. 

I open this issue to share some experience of initially trying OpenMP in Owl. If you observe different behaviour on your machines, I'd be glad to discuss about it.

**Comment by ryanrhymes** [comment]
Thanks for reporting this. I think for the time being it is safer to compile OpenBLAS with `USE_OPENMP=1`.

About the benchmarking, I suggest that we build a new set of tests in perftest folder. DNN is not really ideal for fine-grained performance benchmarking and debugging, even though it gives a rough understanding about certain optimisation I have done to the core.
