### ISSUE TITLE
slice questions

### ISSUE THREAD

**Issue by nilsbecker** [owlbarn/owl#29]
some questions that did not get mentioned in the tutorial: 

[edited after actually trying it out... sorry for unnecessary questions before] 

a) it might be a good feature to have *views* as well, which always share data? 

b) what about increasing/decreasing the rank of an array? something like `a[:,2,:]` or `a[:, np.newaxis]` in numpy? 
a non-automatic version of rank reduction would be a separate `squeeze` function which takes all slice dimensions of length 1 and eliminates that dimension from the array, keeping all the same data. i.e. if the shape is `[|3;1;4|]` it will be `[|3;4|]` afterwards. for typing reasons this function could only be Ndarray -> Ndarray. analogous functions could exists from matrices to vectors.
alternatively, the Ndarray version of `slice` could get an optional boolean `?squeeze` argument.
for rank increase one could have something like `increase_rank 1 a` which makes a shape `[|3;1;4|]` out of `[|3;4|]`.  again, only for Ndarray. for vectors to matrices the functionality is probably already there. 

i believe increasing/decreasing the rank is important especially in the absence of general broadcasting, so that arrays can be brought into the same shape easily before combining them elementwise.

c) how about indexing a general list of elements, e.g. indices `1,2,4,4,3` along a dimension of an array? 

this seems to require a different syntax; the list syntax is already taken for slicing. 
would it be feasible/desirable to accommodate this list indexing in some way? when trying to build this into the `slice` function, one could use an array `[|1;2;4;4;3|]`. but i guess it's difficult to allow for either a slice specification as an `int list` or a direct index set as an `int array` as an argument to the slice function, without having to put them into a variant type like `Slice_spec of int list | Index_set of int array`. so that solution would require very verbose syntax i fear. (for comparison, numpy has the colon syntax for slice specs and also allows a list syntax for explicit indices). 

another option would be to have a separate function for index lists, in addition to `slice` for index ranges. this would probably mostly work, but it would be impossible to mix slicing and set indexing along different dimensions of the same array. (what `a[:,[1,2,1]]` in numpy does). maybe it's acceptable to have to do it separately? although it would probably allocate intermediate arrays.

potentially the following would be a concise enough syntax: only one `slice` function, but a constructor S with two arguments for regular slices,  one Ss with three arguments for strided slices and a constructor Il with a list argument for index lists? something like `general_slice [S (1, 3); Ss (0, 4, 2); Il [1;2;4;4;3]] x` is relatively cumbersome to type compared to numpy; but maybe it would be tolerable?
one could reserve short function names which just apply the constructors, to be able to write `general_slice [s 1 3; s 0 4 ~by:2; il [1;2;4;4;3]]`; this may be acceptably concise? but it is a bit intrusive, claiming the symbol `s` for example seems excessive.

just a collection of thoughts... i hope they're helpful

**Comment by nilsbecker** [comment]
updates..

**Comment by ryanrhymes** [comment]
Hi @nilsbecker , I have read through your comments. They are valid and make sense, really appreciate them. I have faced several design decisions when working on the slicing function. Typing can certainly provide a workaround of the functions you suggested, especially if you want to slice along a specific set of indices. 

However, I have been avoiding to introduce too many constructors since it adds burden in order to memorise them. One possible solution is: 1) implement a more general slicing def and function for more flexibility (typing needed); 2) implement a more specific slicing function for set of indices so it can be composed with current slicing fun (performance degradation).

Before deciding which direction to go, I would like to accumulate more feedback and comments. If it turns out there is really a great demand on certain functionality, it will certainly be implemented. Of course, all thoughts, ideas, and comments are welcome, as always.

**Comment by nilsbecker** [comment]
hi, yes, i agree that there is a decision to make and it's not easy to find the best compromise. i agree with waiting for more feedback/practical experience. at these early stages i guess it's important to keep the options for the best api design open.

the strict typing discipline in ocaml sometimes requires a more verbose style than a non-typed language would allow. i think in general this is still a price well worth paying. some extra characters are not all that bad, if the function names are intuitive and easily memorized. in the case of array slicing i would argue that it's used often enough that one could expect the user to memorize a few constructors.

to get really concise specialized syntax in ocaml would probably require a ppx extension. but there is apparently also a maintainability issue with that (see recent mailing list discussions). so i think a well thought-out api without ppx should probably be the first step, and once that is stabilized one can think of adding ppx.

**Comment by nilsbecker** [comment]
hi, i just saw your new additions to slicing and looked through the new tutorial. it's looking very nice indeed! i think your choice of using lists for the `R` constructor is probably best since then one can have lists of different lengths with a single constructor to memorize.

some thoughts i had while reading:

-  in the tutorial here:
```
It is not necessary to specify all the definitions for all the dimensions, get_slice function will also expand it by assuming you will take all the data in higher dimensions. E.g., x has the shape [ 2; 3; 4 ], if we define the slice as [ [0] ] then get_slice will expand the definition into [ [0]; []; [] ]
```
i think you still want the `R` constructor?

- {get,set}_slice_simple could also be called {get,set}_slice_range which might be more descriptive?

- a full dimension is presently given by `R []` -- have you considered adding a constructor `All` for this case? E.g. `get_slice [All; I 2]`?

- the tutorial does not mention whether or not a copy is made by `get_slice*`. i assume yes? if so, do you think views which are analogous to slices but without copy would be a good feature? (i think probably yes since they may allow avoiding allocating intermediate matrices in cases where speed is important)

- maybe one or two examples for the full slice function with constructors in the tutorial?
