### ISSUE TITLE
`Owl_opencl_context.eval` has a bug

### ISSUE THREAD

**Issue by nomaddo** [owlbarn/owl#293]
In `owl_opencl_context.ml`, function `eval` has a bug:
https://github.com/owlbarn/owl/blob/master/src/opencl/owl_opencl_context.ml#L147

This function always abort if `param` includes `F` cases (see result of `run_raw_opencl_03` in `example/opencl_contest.ml`).

This function has two problem:

- For `F` case, the size (third argument) passing to `clSetKernelArgument` is wrong. Now it passes `sizeof_float_ptr`, but should be `sizeof_float` or `sizeof_double`.
  To send a data of type `float` (not `float *`), it it a right way as like 

```c
  float f = 3.14;
  ret = clSetKernelArg (kernel, 1, sizeof(float), (void*) &f);
```

- Scalara floating-point value is represented as only `F` ignoring required type!!! 
  Arrays are divided into `F32` and `F64`, so it is easy to decide the size to pass `clSetKernelArg`. But in this implementation, the passing size of scala values cannot be determined.
  We need to divide scalar value type `F` into two types like `F` and `D`, and so on......

**Comment by nomaddo** [comment]
> So we do not need two constructors, but we probably do need to do the type conversion in C code, e.g. from double to single if necessary.

Thanks, you're right. With OpenCL 2.0 or later, `clGetKernelArgInfo` can query required types of kernel arguments if you exec `clBuildProgram` with `-cl-kernel-arg-info`.

**Comment by ryanrhymes** [comment]
OpenCL will become obsoleted soon due to our new ongoing project : https://github.com/owlbarn/owl_symbolic @jzstark
