### ISSUE TITLE
Time complexity of top and bottom functions for Ndarray

### ISSUE THREAD

**Issue by pvdhove** [owlbarn/owl#305]
The time complexity of [`_search_close_to_extreme`](https://github.com/owlbarn/owl/blob/master/src/owl/dense/owl_dense_ndarray_generic.ml#L5331), which is used by functions `top` and `bottom`, is currently O(n * k), where n is the number of elements in the ndarray and k is the number of extreme elements to find. However, a time complexity of O(n * log(k)) is achievable by replacing the array `vls` by a min/max heap of bounded size k (while keeping the same space complexity).

I don't think that there is a standard heap implementation in OCaml - would it make sense to implement a heap in Owl (in a file `base/misc/owl_utils_heap.ml` for instance)? If not, how would you structure this addition?

**Comment by ryanrhymes** [comment]
I agree, the current `_search_close_to_extreme` has a very naive implementation. What you propose sounds very good so please go for that 👍

`base/misc/owl_utils_heap.ml` is the right place to implement the heap functionality, similar to `owl_utils_array.ml`.
