### ISSUE TITLE
Duplicated node IDs in CG module

### ISSUE THREAD

**Issue by pvdhove** [owlbarn/owl#319]
In the computation graph module, the current strategy to give each node a different id is to keep a [global counter](https://github.com/owlbarn/owl/blob/master/src/base/core/owl_graph.ml#L22) and increment it every time a node is created. However, it is possible to obtain two nodes with the same id: for instance, when loading NN weights (that were saved by another program), these weights are nodes that already have an id, but the new program will assign ids from 0 again. Thus some distinct nodes can end up having the same id. The same problem occurs for the same reason with the `block` ids.

This can cause some trouble since most of the graph functions rely on ids to distinguish nodes. For example, [graph traversals](https://github.com/owlbarn/owl/blob/master/src/base/core/owl_graph.ml#L134) use the id of the node to check whether a node has already been visited. This can prevent some nodes from being visited.

An easy solution would be to hash the node instead of its id, using either OCaml's polymorphic `hash` function or by defining a custom hash function for nodes. It looks difficult to really ensure uniqueness of ids when loading static graphs/weights from memory.

**Comment by ryanrhymes** [comment]
I agree this is an issue, thanks for pointing it out. Hashing is a good solution. But simply hashing the whole node may not work because the hash value will change if you modify some fields in the nodes (which is possible since owl's graph container is mutable). So if we go for hashing solution, a customised hashing function is better, but we need to decide what to hash.

Do you think using security hash to generate a random id (long enough to avoid collision) is a solution? This may require us to change the type of `id` from `int` to `string`. Simple random number is also a solution, but the probability of collision will be much higher.

**Comment by pvdhove** [comment]
Would there really be a real advantage of using random strings rather than random ints? It is unlikely to get more than 10^5 nodes in a computation graph, and using [Random](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Random.html).`self_init ()` and `Random.bits ()` would generate a random id between 0 and ~10^9 that can be used directly for hashing (and we can still use physical equality of nodes to check for equality, so a collision does not make the algorithm wrong). Even if there are a few collisions, generating and hashing ints is faster than strings and that would probably compensate for the few more collisions?

**Comment by hadils** [comment]
What about using uuids?

**Comment by pvdhove** [comment]
I think what matters here for efficiency is the value of the hash function modulo the number of buckets in the hashtable, which in practice will be much smaller than 2^30. If I am right that in this case uniqueness of ids is not really important since physical equality can be used to distinguish nodes, then I think it does not matter much to use a 32-bit integer or a 128-bit integer?

**Comment by ryanrhymes** [comment]
@hadils uuid will certainly do. @pvdhove agree, it is a relatively safe assumption that the graph won't grow insanely huge, so random int is a sane choice, let's go for that?

**Comment by pvdhove** [comment]
OK! I will fix that soon.
