### ISSUE TITLE
formatting of lists of matrices

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#32]
I'm an OCaml newbie; Owl makes it a lot more useful for me.  Thanks very much.

I like that matrices are nicely formatted by default in repls.  That's very nice.  (By contrast, in Clojure's core.matrix, the way that matrices are displayed depends on which matrix implementation you're using, and some are not displayed in an optimal manner.  You have to pass matrices to a pretty-printing function to assure a nice display.)

However, when I put matrices in a list, what's displayed is a bit strange.  Here's a list of five 2x2 matrices In a standard ocaml 4.04.0 toplevel in a terminal window on MacOS: 
```
- : Owl.Mat.mat list =
[   C0 C1
 R0  2  4
 R1  1  0
;    C0 C1
            R0  0  6
            R1  0  3
;
    C0 C1
 R0  0  2
 R1  3  4
;    C0 C1
            R0  6  4
            R1  4  2
;
    C0 C1
 R0  0  3
 R1  3  6
]
```

Here is a similar list of five matrices in utop:
```
   C0 C1
R0  2  4
R1  1  4
   C0 C1
         R0  5  0
         R1  0  0
   C0 C1
                  R0  0  1
                  R1  1  4
   C0 C1
                           R0  0  1
                           R1  3  3
   C0 C1
                                    R0  0  3
                                    R1  3  5
- : mat list = [; ; ; ; ]
```
I guess there's some kind of interaction between the way that Owl is formatting matrices and the way the repls are formatting lists.

This is obviously not an urgent issue.

**Comment by ryanrhymes** [comment]
Hi @mars0i many thanks for your feedback! You are right that currently if you wrap matrices in tuple or list or array, it will mess up with pretty print function a bit. This is definitely not ideal so I will look into this issue asap.

**Comment by mars0i** [comment]
After thinking about it further, I'm worried that what's required would be changes to ocaml or utop, but if you are able to create a solution within Owl, that would be very nice.

**Comment by ryanrhymes** [comment]
> After thinking about it further, I'm worried that what's required would be changes to ocaml or utop, but if you are able to create a solution within Owl, that would be very nice.

There is no need to hack into `utop`. The output wasn't aligned well because some internal states of Formatter were not properly reset. Now the problem has been solved. You can try the master branch (either install from github by yourself or simply pull our docker image).

With the changes, now you should be able to see the following outputs in `utop`.

```ocaml
utop # [|x;x;x;x|];;

          C0       C1        C2       C3                                                                                                                                           R0 0.0748959 0.750436  0.105741 0.582378                                                                                                                                             
R1  0.916661 0.067033 0.0733354 0.780014
R2  0.588304 0.552774  0.879661 0.361532
R3  0.726633 0.633897  0.382892 0.434261


          C0       C1        C2       C3
R0 0.0748959 0.750436  0.105741 0.582378
R1  0.916661 0.067033 0.0733354 0.780014
R2  0.588304 0.552774  0.879661 0.361532
R3  0.726633 0.633897  0.382892 0.434261


          C0       C1        C2       C3
R0 0.0748959 0.750436  0.105741 0.582378
R1  0.916661 0.067033 0.0733354 0.780014
R2  0.588304 0.552774  0.879661 0.361532
R3  0.726633 0.633897  0.382892 0.434261


          C0       C1        C2       C3
R0 0.0748959 0.750436  0.105741 0.582378
R1  0.916661 0.067033 0.0733354 0.780014
R2  0.588304 0.552774  0.879661 0.361532
R3  0.726633 0.633897  0.382892 0.434261
```

Thanks for the feedback again, and these changes will of course appear in the next release on opam.

**Comment by mars0i** [comment]
Thanks very much!  At the moment I'm mostly using owl to explore ideas in a repl, so this is extremely helpful.

There are still some quirks to the formatting, but I don't think they're important.

In utop, the list or array notation prints out after the matrices:
```

         C0       C1        C2       C3
R0 0.293298 0.313454 0.0634332 0.329815
R1 0.171872 0.392842  0.196419 0.238867
R2 0.322737 0.206121  0.264449 0.206693
R3 0.249079 0.265668  0.295237 0.190017


         C0       C1        C2       C3
R0  0.26624 0.121318 0.0474497 0.564993
R1 0.243216 0.305981   0.15424 0.296563
R2 0.288217 0.136218  0.302952 0.272613
R3 0.223914 0.311095   0.28623 0.178761

- : mat list = [; ]
```
This looks a little bit odd, but perhaps it's preferable.

In a standard ocaml toplevel, the matrices are embedded in list or array notation, but the first header line is shifted:
```
- : Owl.Mat.mat array = [|
                                    C0        C1       C2        C3
R0 0.0583213  0.327187 0.340321  0.274172
R1  0.319603  0.260801 0.137938  0.281658
R2 0.0715143 0.0288425 0.727605  0.172038
R3  0.474213  0.252846  0.19385 0.0790907

;

         C0       C1       C2       C3
R0 0.218161 0.117618 0.393385 0.270836
R1 0.251668  0.10776 0.142329 0.498243
R2 0.104087 0.175379 0.453084  0.26745
R3 0.261103 0.205069 0.296186 0.237641

;

         C0         C1       C2       C3
R0 0.226336 0.00852521 0.403554 0.361585
R1 0.185176  0.0345119 0.402629 0.377683
R2 0.262234 0.00939646 0.335595 0.392775
R3 0.295586   0.193917 0.312658 0.197838

|]
```

(It would certainly be reasonable to ignore formatting the traditional ocaml toplevel given that we have utop.  In my case, I prefer utop, but I'm also experimenting with a [custom ocaml toplevel](http://www.alliot.fr/fbbdet.html.fr) that implements interval arithmetic, and I don't yet know enough to build that into a custom utop.  I'm not sure whether I'll use interval arithmetic with owl in the end, though, so it might not matter.  However, now you know why I test in the traditional toplevel as well.  In any event, utop is sufficient for my needs with owl, and even if I need to use owl in a non-utop repl, having a shifted header line at the top is not going to be a problem.  (The project I'm working on is in an early,study-and-exploration stage.)

**Comment by mars0i** [comment]
Possibly relevant: https://discuss.ocaml.org/t/dissociated-ugly-output-with-install-printer-in-utop/425
