### ISSUE TITLE
Proposal: posv_flip

### ISSUE THREAD

**Issue by dc-mak** [owlbarn/owl#326]
In column-major Fortran world, `posv` solves AX = B.

To make this work for the row-major C-world [LAPACKE actually creates a transposed temporary copy of A and B and passes *that* into LAPACK](https://github.com/xianyi/OpenBLAS/blob/ce3651516f12079f3ca2418aa85b9ad571c3a391/lapack-netlib/LAPACKE/src/lapacke_dposv_work.c#L47-L92) It then tranposes the result back into the original matrices. (Side note: if A is assumed to be pos. def. I don't know why a transposed copy of it is being made but oh well).

I was writing a problem where I wanted to solve XA = B in Owl, I think we should offer a `posv_flip` (or any better name), currently the easiest way of doing this I can think of is to transpose A & B, call `posv`, then tranpose again. But this is a bit grim, because I also know how LAPACKE handles it from my call to `posv`.
I have this code in my project right now:
```ocaml
  (* Compute X = B A^-1 using A'X' = B' / X = (A'^-1 B')'
     But make it so transposing is just a Row/Column order flipping *)
  let posv_flip (M a : z mat) (M b : z mat) =
    let (n,_) = Owl.Mat.shape a in
    let (k, n') = Owl.Mat.shape b in
    let () = assert (n = n') in
    let lda = n in
    let ldb = n and nrhs = k in
    let layout = 102 (* Interpret as Fortran layout *) in
    let conv = Ctypes.bigarray_start  Ctypes_static.Genarray in
    let ret = Owl_lapacke_generated.dposv ~layout ~uplo:'U'
                    ~n ~nrhs ~a:(conv a) ~lda ~b:(conv b) ~ldb in
    check_ret ret;
    (M a, M b)
  ;;
```
which exactly solves XA = B. I'm pretty proud of this :P What do you think about adding something like this to Owl? There are probably a few more situations where LAPACKE has to deal with this sort of thing, so there might be even more similar opportunities like these.

**Comment by ryanrhymes** [comment]
It looks good to me, so go ahead with PR (remember to add a unit test if possible). Do you think `Linalg` is the right place to add this function? You can extend your current implementation to support other number types.

Regarding the name, Matlab uses `mldivide` and `mrdivide`. `mldivide` corresponds to Owl's `Linalg.linsolve` but we can certainly make an alias if you decide to use `mrdivide`. I don't know the naming in Scipy and Julia, or R, but I am open to suggestions.
