### ISSUE TITLE
Why README was basically removed?

### ISSUE THREAD

**Issue by XVilka** [owlbarn/owl#333]
See https://github.com/owlbarn/owl/commit/493f4a5cbb1bbef75218b610badcb95717f7906d

**Comment by XVilka** [comment]
Not to mention that the site at that link is empty with just "Hello world".

**Comment by ryanrhymes** [comment]
Hi, because most content in readme is already outdated and requires significant rewriting. komposio website is under construction at the moment.

For full document, you should access from ocaml.xyz. It is here : http://ocaml.xyz/chapter/index.html

**Comment by ryanrhymes** [comment]
I agree it looks a bit too empty at the moment. I will try to add some more up-to-date information during the weekend. However, ocaml.xyz in future will be the main site hosts owl's documentation and other learning materials.

Reopen the issue please if you think more needs to be done, thanks.
