### ISSUE TITLE
Arr.init_nd does strides incorrectly

### ISSUE THREAD

**Issue by emengd** [owlbarn/owl#334]
Hi,

I hope this hasn't already been fixed, as I had a lot of trouble installing Owl and I don't really remember what version I am using (it's a pinned and patched dev version). Apologies if I'm late.

Anyway, the function Owl.Arr.init_nd appears to be incorrect:

```
utop # let a = init_nd [|2; 5|] (fun a -> (float a.(0)));;
val a : arr = 
   C0 C1 C2 C3 C4 
R0  0  0  1  1  2 
R1  2  3  3  4  4 

utop # let a = init_nd [|2; 5|] (fun a -> (float a.(1)));;
val a : arr = 
   C0 C1 C2 C3 C4 
R0  0  0  0  0  0 
R1  0  0  0  0  0 
```

The first index is incremented as if the dimensions were reversed, and the second one never is.

**Comment by ryanrhymes** [comment]
I think this has been fixed already, at least master branch calculate this correctly. The version on opam is quite outdated, I will try to release one whenever i have time.

Please reopen this issue in case you still cannot produce correct result with master branch.

**Comment by emengd** [comment]
Just posting to confirm the master branch does this correctly.
