### ISSUE TITLE
Slicing operations fail on large matrices

### ISSUE THREAD

**Issue by ejaasaari** [owlbarn/owl#337]
Using owl from the current master branch, slicing matrices that have more than 2^31 elements seems to cause reads from invalid memory addresses. For example, this snippet mmaps an nxn matrix and writes ones to the last row when n = 46340 (< sqrt(2^31)):

```ocaml
module MX = Owl.Dense.Matrix.S

let mmap_mat sz : MX.mat =
  let fh = Unix.openfile "test" [ Unix.O_RDWR; Unix.O_CREAT ] 0o644 in
  Unix.map_file fh Float32 C_layout true sz

let () =
  let n = 46340 in
  let x = mmap_mat [|n; n|] in
  MX.set_slice [[n - 1; n - 1]] x (MX.ones 1 n);
  MX.get_slice [[n - 1; n - 1]] x |> MX.print ~max_col:10
```

For n = 46340 this works as expected:
```
$ ./a.out

   C0 C1 C2 C3 C4     C46335 C46336 C46337 C46338 C46339
R0  1  1  1  1  1 ...      1      1      1      1      1
```

However, changing to n = 46341 (> sqrt(2^31)) causes a segfault:
```
$ ./a.out
[1]    6160 segmentation fault  ./a.out
```

**Comment by mseri** [comment]
Is this due to the fact that Owl uses the non tail-recursive `List.map` here: https://github.com/owlbarn/owl/blob/master/src/owl/core/owl_slicing.ml#L112 ?

**Comment by ryanrhymes** [comment]
Fixed in https://github.com/owlbarn/owl/pull/458
