### ISSUE TITLE
boolean indexing

### ISSUE THREAD

**Issue by nilsbecker** [owlbarn/owl#34]
in light of the recent slicing additions here is another feature from numpy that could be potentially useful: boolean indexing.

e.g. `a[a>5]` where a is a numpy array, and `a>5` is a boolean array that gives elementwise truth values of the comparison and has the same shape as `a`. 
then the indexing returns a flat, one-dimensional array of only the entries that are `True`. in numpy this is used a lot like this: `a[a>5] = 5`, i.e. for assignment. but in image processing, bitmasks such as `a>5` itself are also useful.

i'm not sure it's necessarily a good idea to try and copy the assignment idiom in owl. for one, i don't think there is an appropriate boolean bigarray version. then, to use it for assignment, the array would need to be a view. it might be better instead to construct some kind of an iterator function that does this conveniently. currently, what i would try would be `Mat.iteri (fun i j v -> if v > 5. then Mat.{i,j} <- 5.) a` which seems rather long?

**Comment by ryanrhymes** [comment]
OK, I see. Currently, there are several ways to achieve that in Owl. You already mentioned one, i.e., using `iteri` function. Another solution is using `filter` function which returns a list of indices that satisfy the predicate.

```ocaml
let x = Mat.uniform 5 5;;
Mat.filter (( < ) 0.5) x;;
```

Another solution is using Owl's operators, this works fine for simple predicates (such as `=.`, `>` ...). I will use `Ext` module for example.

```ocaml
open Owl.Ext;;
let x = Dense.Matrix.D.uniform 5 5;;
let y = x >. F 0.5;;
```

`y` is a `0`/`1` matrix which has the same meaning of a boolean matrix. For a similar example to the one you gave before, `a[a>0.5] = 5`, you can simply write

```ocaml
(x >. F 0.5) * F 5.;;
```

**Comment by nilsbecker** [comment]
thanks! that is very informative.

`map` is nice of course but allocates a new matrix, which could sometimes be undesired. 
`filter` could be a general idiom, but how do you then assign? by iterating as in `List.iter (fun inds -> x.{inds} <- 5.) indlist` i guess? this is a little verbose (could be maybe a little nicer if `Mat.set` accepted tuples of indices). it could be potentially nice to have filter return a generator instead of a full list, so that iterating over a filter would effectively be a fused loop? (something like c-cube's `Gen`)

i was not aware of the new operators. shiny! 
quick comments: you mention in the tutorial that the `$+` etc operators are problematic; maybe one could throw those out right from the start? reordering scalar addition etc. does not seem to be a big deal...
`<>` and `!=` are usually structural vs physical, is this still true? i recently learned that since `nan <> nan` but `nan == nan` this distinction is also important for direct floats. for full matrices i guess, too. (also, would one then not need `==.` and `==` in addition?)
the fact that `x>.y` returns ints might be a bit wasteful of memory, but i don't think we have boolean bigarrays, and it's not clear what to do without them. is it possible in principle to make a custom bigarray module that adds boolean arrays, in C? or would that require some privileged support from the compiler to work?

ext module: this looks fancy. i'll try to understand how the types work out.
