### ISSUE TITLE
Optimise consecutive calls to Stats.quantile

### ISSUE THREAD

**Issue by pveber** [owlbarn/owl#341]
The [current implementation](https://github.com/owlbarn/owl/blob/master/src/base/stats/owl_base_stats.ml#L554) is not efficient when one wants to compute several quantiles at a time, because it will sort the sample at each call. What about the following simple change:
```ocaml
let quantile x =
  let y = sort ~inc:true x in
  let n = Array.length y in
  fun p ->
    let index = p *. [...]
```
with a corresponding explanation in the doc?

BTW, there used to be a check on `p` (should be between 0 and 1), one could raise `Invalid_argument` if not.
I can send a PR if that helps.

**Comment by ryanrhymes** [comment]
The proposal looks good to me, please do submit a PR. many thanks!

my apologies for the delay in replying :)

**Comment by pveber** [comment]
No worries, here it is!
