### ISSUE TITLE
remove -llapacke flag (linux)

### ISSUE THREAD

**Issue by ghennequin** [owlbarn/owl#344]
I think l54 in `src/owl/config/configure.ml` should be modified / removed so as *not* to request `liblapacke` from linux systems where OpenBLAS has been installed from source and already include Lapacke. At the moment this breaks compilation for me, as I don't have such a thing as `liblapacke`.

```ocaml
let get_default_libs c =
  let ls = [
    "-lopenblas";
    "-lm";
  ] in
  get_os_type c |> function
  | ("linux"|"linux_elf") -> "-llapacke" :: ls
  | (""|"macosx"|"mingw64") -> ls
  | s -> failwith ("get_default_libs: unknown system "^s)
 
```

Removing ` "-llapacke" ::` from the relevant line fixes my compilation problem. Took me a while to figure this out :scream: 

I don't know whether this would break compilation for other linux systems where lapacke has to be installed separately.

**Comment by igarnier** [comment]
I do the same on my local Owl install. My understanding (probably wrong) is that the system package for Openblas works on most linux distros and that this line is fine on those systems. As you say, on some distros (such as Ubuntu), one has to install Openblas by hand and then this line causes problem. 
To fix this cleanly, one would have to inspect the ldconfig cache and check whether the version of libopenblas currently used for linking exports the right symbols, or something to that effect.

**Comment by ryanrhymes** [comment]
Numerical libraries on different platforms are very inconsistent and broken. The binary installation of openblas on ubuntu does not include lapacke so we have to compile from source. I can temporarily comment out this line.

In the long run, we need an expert to redesign owl's building and installation flow, which by itself is worth another standalone project.

**Comment by ghennequin** [comment]
Perhaps we could temporarily rely on the user setting an environment variable, e.g. `LAPACKE_IN_OPENBLAS` ? This way compilation will still work for those who need the `-llapacke` flag but will not break for me if I set the environment variable.

**Comment by ghennequin** [comment]
Any thoughts on this idea of allowing an environment variable to override the defaults in `src/owl/config/configure.ml`? It seems to me that this would be a good short-term solution, not breaking what works on Ubuntu currently.

**Comment by ryanrhymes** [comment]
Sorry for the delay, I didn't forget this :) In the end, I removed that lapacke link flag. The original reason of introducing that flag is LAPACKE/CBLAS binary installations are very inconsistent on different platforms. However, using this flag opens another can of worms in the end.

The recommended installation is still building OpenBLAS from source, which will solve most of the installation issues. If needed, -llapacke flag can be added in `src/owl/dune` file directly under `c_library_flags`.

I am closing this issue, but feel free to repoen it in case there are further issues. Thanks.

**Comment by mseri** [comment]
I also have a version using pkg-config that works nicely also on ubuntu without hardcoded paths (but manual openblas installation) and a version that compiles openblas (as I did in eigen) when compiling owl (that maybe would be the slowest but most consistent optionj). None of this solution is good though, they go through differrnt hacks to workaround the inconsistency
