### ISSUE TITLE
Numerical robustness of balance_last

### ISSUE THREAD

**Issue by pveber** [owlbarn/owl#347]
The following code fails for me:
```ocaml
let u = [|7.29051884672767705e-28; 7.40891406114041623e-19; 7.8974585653914162e-27;
    6.74931722499952811e-27; 1.96567242595806183e-18; 1.99759418829810833e-09;
    9.00957709439775126e-18; 7.69975469891059e-18; 5.44630568871032146e-27;
    5.53475162082589e-18; 7.14562067029471901e-27; 7.26166281614767e-18;
    3.40581066900184642e-26; 1.76422660684586938e-18; 1.79287696675020245e-09;
    8.08625861896575203e-18; 6.91066930614189608e-18; 9.84019855846523357e-10;
    0.999999958920365861; 4.51021371572784489e-09; 3.85451380633076905e-09;
    5.57697548253416743e-18; 5.6675434090004686e-09; 2.84750345476462241e-17;
    2.43353022074415654e-17; 6.00096499322304467e-18; 6.09841835106380515e-09;
    2.7505171256294709e-17; 2.35064387154075702e-17; 6.62930524914401317e-27;
    6.73696260890209106e-18; 3.03851424471216853e-26; 2.60227107878253518e-26;
    8.19698787626752916e-18; 8.33010379906068e-09; 3.75705500032367818e-17;
    3.21085014652355746e-17; 4.22071117495635736e-26; 4.28925389538807169e-17;
    1.04857628916290599e-25; 8.96133096150629102e-26; 3.89639425302617225e-26;
    3.95967019196240566e-17; 1.31783685040006345e-25; 1.12624825529808348e-25;
    1.2664323265349806e-28; 1.28699869924975191e-19; 5.80463937719803923e-28;
    4.96075441996169876e-28; 7.71899620480556344e-18; 7.84434972714204e-09;
    3.5379695143730131e-17; 3.02361555328812682e-17; 7.34588525560146473e-27;
    7.46517960274637435e-18; 1.49279215819264218e-25; 1.27576836720746576e-25;
    2.33797209106778106e-26; 2.37593985643049289e-17; 1.07159969713535906e-25;
    9.15809335252883654e-26|];;

Owl.Utils.Array.balance_last 1. u;;
```
with an assertion error on this code:
```ocaml
let balance_last mass x =
  let k = Array.length x - 1 in
  let q = ref mass in
  Array.mapi (fun i a ->
    assert (!q >= 0.);
    if i < k then (
      q := !q -. a;
      a
    )
    else !q
  ) x
```
Given the numbers, this is obviously due to numerical (im)precision, but I have no idea how one should (could?) fix this. I'm just reporting in case there is something that can be done. I was bitten by this while sampling categorical variables, in the mean time I've just set small values to actual zeros.

**Comment by ryanrhymes** [comment]
Thanks for reporting this, I don't have an immediate solution at the moment, need to do some research later.

**Comment by ryanrhymes** [comment]
This seems a common problem, have you tried other languages or libraries. I remember the old matlab did not have kahan sum to compensate the round up error, but not sure about their new version.

There is some code in the underly C part of Owl dealing with float number overflow and underflow (relies on fenv.h), unfortunately it is not fully implemented. Some code is in cephes, some in owl itself. You can search 'underflow' in owl repo to find them. or you can have a look at this file https://github.com/owlbarn/owl/blob/a60b6b838902300a11172e4376aac79ded44fcea/src/owl/stats/owl_stats_extend_misc.c

There are better algorithms to provide better accuracy, when i was writing up stats module, i was thinking to automatically switch to better algorithms in case an underflow/overflow has been detected. Honest, I didn't get this part properly designed in owl's core due to time constraint, if you want to take a stab at this, i can certainly help you.

**Comment by pveber** [comment]
If I can help, I'd be glad to! I know pretty much nothing about numerical calculation so bear with me :). I have been looking at `R`'s [multinomial sampling implementation](https://github.com/wch/r-source/blob/trunk/src/nmath/rmultinom.c#L47), and it looks pretty similar to owl's except from two points:
- extra precision (long double) for the moral equivalent of `norm` and `acc_p`
- initial check that probabilities sum to 1

The last item looks better to me than using the `balance_last` function. Notably, `multinomial_rvs` does not check that the sum of its `p` argument is one, and IIUC `balance_last` ensures this is the case, by discarding the last element of `p` and replacing it by the complement to 1. If one provides a `p` that sums to more than 1, either she gets an error which is difficult to understand, or worse she doesn't get any error at all if it's the last element which is "too big".

What about checking that `p` "reasonably" sums to 1 and don't use `balance_last` at all?

**Comment by ryanrhymes** [comment]
That would be great, please do give it a try. Many of the algorithms included in Owl are from [Numerical Recipes](http://numerical.recipes/oldverswitcher.html) book, they are classic but may not reflect the newest and best choice nowadays. If you find better options, please do improve them and PR, that is actually recommended way to start and get familiar with Owl.

**Comment by pveber** [comment]
For the record, scipy works like the current implementation in owl, see [this doc](https://github.com/scipy/scipy/blob/4c0eed82eb0a40bec3e39a7a5f9cb0ed42617a81/scipy/stats/_multivariate.py#L2865). The code corresponding to `balance_last` can be found [here](https://github.com/scipy/scipy/blob/4c0eed82eb0a40bec3e39a7a5f9cb0ed42617a81/scipy/stats/_multivariate.py#L3012).

I don't really get why this is a good option, compared to R's implementation. One possibility would be that this is a way to catch numerical difficulties, while renormalizing to 1 would hide it (or add extra imprecision).

**Comment by pveber** [comment]
The [GSL version](http://git.savannah.gnu.org/cgit/gsl.git/tree/randist/multinomial.c#n43) is the same than R's, and is based on the so-called conditional distribution method in (Davis 1993)

[Davis 1993] The computer generation of multinomial random variates

**Comment by pveber** [comment]
scipy's interface was chosen to be similar to numpy: scipy/scipy#5410
See the discussion where various people say they're not happy with this convention of discarding the last probability.

The [actual PR](scipy/scipy#6375) that introduced the current implementation mentions the above discussion, but keeping on the same track.

**Comment by pveber** [comment]
And finally, [numpy implementation](https://github.com/numpy/numpy/blob/cc8b978cc3c0abe57c3784b99302a04f2c2701d9/numpy/random/mtrand/mtrand.pyx#L4587)

**Comment by pveber** [comment]
As I see it, owl's current implementation is very close to the one in the GSL. It computes the sum of input probabilities (`norm` variable), and it seems to me that it doesn't matter that these sum to 1. Playing with `gsl` confirms it:
```ocaml
# let rng = Gsl.Rng.make (Gsl.Rng.default ());;
val rng : Gsl.Rng.t = <abstr>
# Gsl.Randist.multinomial rng ~n:100000 ~p:[|1. ; 2.|];;
- : int array = [|33251; 66749|]
```
This seems very natural to me, and much less confusing and error prone than ignoring the last element of the probability vector.

So in summary, it would be enough to remove the call to `balance_last` in `multinomial_rvs`:
```ocaml
let multinomial_rvs n ~p =
  let k = Array.length p in
  let _p = Genarray.create float64 c_layout [|k|] in
  let _s = Genarray.create int32 c_layout [|k|] in
  Owl_utils.Array.balance_last 1. p |>
  Array.iteri (fun i a -> Genarray.set _p [|i|] a);
  _multinomial_rvs ~k ~n ~p:_p _s;
  Array.init k (fun i -> Genarray.get _s [|i|] |> Int32.to_int)
```
The same is true IMO for the log pdf.
