### ISSUE TITLE
Add statically size-checked arrays?

### ISSUE THREAD

**Issue by cfhammill** [owlbarn/owl#374]
[Slap](http://akabe.github.io/slap/) has these and they don't seem too heavyweight, so it might be interesting to build add such (optional) functionality on top of the existing array infrastructure.  (Would be willing to contribute ... shouldn't take long :) )

- @bcdarwin said this

**Comment by bluddy** [comment]
This is interesting, but also quite limited, I think. There's no relationship between different sizes: if you slice a 3-dim tensor, it can't statically figure out whether it should produce a 2-dim tensor or a 1-dim tensor (unless you somehow invoke metaprogramming in the function call). 

Additionally, functions that add/remove a dimension (squeeze and unsqueeze and similar) cannot produce the dimensionally-correct annotated tensors.

This all works better with Peano numbers and type level computation uses type classes. Perhaps it will be possible with modular implicits.

**Comment by ryanrhymes** [comment]
@cfhammill It is an interesting proposal, do you think this feature will be independent from existing owl's implementation? If not, how much it will affect current design? Can this be done as a lib depending on owl's core? We can possibly start a sub project like others zoo, mrcnn, ode, and etc.
