### ISSUE TITLE
"library not found for -llapacke" after configuration update

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#389]
Hi @mseri, many thanks for the recent PR #385 for cleaning up Owl's configuration. However, I've just pulled the new code and compiling it on my MacBook results in error:

```
ld: library not found for -llapacke
```
I tried to remove it so that the line 174 in config/configuration.ml becomes `if needs_lapacke_flag then [] else []`. Then the error becomes:

```
ld: library not found for -lopenblas
```
The OpenBLAS on my machine is installed to `/usr/local/lib/openblas/`.

 I understand that fixing this kind of issue thoroughly might take some time. I was just thinking if there is any quick quick fix to it.

------

OK, with the help of @mseri, two points for me to fix this issue on my machine:
1. remove `-llapacke` --- shouldn't be necessary now after limiting dune version > 1.2.1
2. By default, the linked library path is `-L/usr/local/lib`, which is wrong, and also leads to the `library not found for -lopenblas` error. Update the PKG_CONFIG_PATH, then this issue will be solved.

**Comment by mseri** [comment]
It is only missing the PKG_CONFIG_PATH. You need to either export or add to your terminar .rc file:
```
PKG_CONFIG_PATH=/usr/local/opt/openblas/lib/pkgconfig
```

It should be enough to do
```
PKG_CONFIG_PATH=/usr/local/opt/openblas/lib/pkgconfig dune build
```

This is as it should be in some sense:
```
$ brew info openblas
openblas: stable 0.3.5 (bottled), HEAD [keg-only]
Optimized BLAS library
https://www.openblas.net/
/usr/local/Cellar/openblas/0.3.5 (21 files, 120.7MB)
  Poured from bottle on 2019-02-15 at 09:49:30
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openblas.rb
==> Dependencies
Required: gcc ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
openblas is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BLAS and LAPACK in the Accelerate framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/usr/local/opt/openblas/lib"
  export CPPFLAGS="-I/usr/local/opt/openblas/include"

For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"

==> Analytics
install: 28,616 (30 days), 104,771 (90 days), 172,739 (365 days)
install_on_request: 2,039 (30 days), 9,152 (90 days), 31,597 (365 days)
build_error: 0 (30 days)
```

**Comment by mseri** [comment]
I wonder if we can directly use accelerate on mac... @ryanrhymes do you know if it can work or if it surely does not work?

**Comment by mseri** [comment]
I am quite surprised that it does not work though, it should have got the right path from the default configuration

**Comment by ryanrhymes** [comment]
> I wonder if we can directly use accelerate on mac... @ryanrhymes do you know if it can work or if it surely does not work?

it is complicated, i recently dropped accelerate framework out from configure.ml because it complicates things more especially before we have a good support to cblas/lapacke and openblas. refer to this https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate

**Comment by ryanrhymes** [comment]
i think both julia and scipy bundle cblas/lapack together in their software. Is it actually a better idea we just pre-compile an openblas for different platform, then bundle it with owl to save all these hassles?

**Comment by mseri** [comment]
Thanks! We could do like we do in eigen and allow to compile it locally as a pre-build step in case is not present or broken

**Comment by mseri** [comment]
(somewhat like what scipy and juila are doing afaik)

**Comment by ryanrhymes** [comment]
I actually tried this before in conf-openblas (by bundling openblas code), openblas takes a long time to compile (> 40 min) which will fail all the travisCI which has a hard time limit (forgot how long though).

**Comment by mseri** [comment]
I think we should move all that from the conf package to owl itself

**Comment by mseri** [comment]
@ryanrhymes we may have found the responsible. Dune needs to be `>= "1.2.1"` for the the lapacke check to be performed properly. I have updated it in the new configurator PR.

**Comment by jzstark** [comment]
Just to confirm that the the issue is indeed with dune version. After upgrading to 1.7.1 version, the Owl source now compiles fine. Thanks a lot for your help @mseri !

**Comment by mseri** [comment]
Thanks @jzstark for the your help in tracking it down. With the last merge I think we can close this issue
