### ISSUE TITLE
Override arch optimizations

### ISSUE THREAD

**Issue by rdavison** [owlbarn/owl#394]
Is there any support or any planned support for being able to override the `-march=native flag`?  I am currently trying to support a continuous integration and delivery pipeline which begins by checking out application source code to a virtual machine in the cloud, building executables, saving the executables to a docker image, and then deploying the docker image to another cloud environment.

Unfortunately, since `-march=native` is hard coded in a few different places [1] [2] [3], it means that when my cloud CI provider encounters internal scaling issues due to rapid growth of their platform, they may upgrade their underlying virtual machines with fancier hardware.  In my case, they upgraded to machines with Intel Xeon processors which supported AVX-512 instructions sets.  This led to binaries being compiled with fancy optimizations which later crashed when deployed to our vanilla x86-64 hardware.

For the time being, we are using a fork with those `-march=native` flags set to `-march=x86-64`, but it would be nice if those settings could be overridable somehow.  Any thoughts? Could perhaps the configurator in `dune` be of any use in this situation?

[1]
https://github.com/owlbarn/eigen/blob/master/eigen/dune#L29

[2]
https://github.com/owlbarn/owl/blob/master/src/owl/config/configure.ml#L81

[3]
https://github.com/owlbarn/owl/blob/master/src/aeos/config/configure.ml#L15

**Comment by mseri** [comment]
We can read environment variables, it would not be hard to allow to override thse by reading them out of `OWL_CFLAGS` when set. That would work cleanly both with opam and manually compiling.

@ryanrhymes what is your opinion in this respect?

**Comment by mseri** [comment]
This would probably also provide a fix for https://github.com/owlbarn/owl/issues/354

**Comment by ryanrhymes** [comment]
env variables is a good solution, we can provide default settings, so I agree.

**Comment by mseri** [comment]
Ok, than this is an easy fix. I will send a PR here and to eigen after #396 is merged

**Comment by mseri** [comment]
@rdavison with the latest eigen and the current master branch of owl, you should be able to override all the C and CPP flags by setting the right env variables (refer to owl and eigen's readmes for the names and the default values). Does this solve your issue?

**Comment by mseri** [comment]
@rdavison with he released eigen and owl you can customise it, see 
https://github.com/owlbarn/owl/blob/master/docker/Dockerfile.ubuntu and
https://github.com/owlbarn/owl/blob/master/docker/Dockerfile.ubuntu.arm as examples of use. Let me know if this solves your issues

**Comment by rdavison** [comment]
@mseri: Hey, thanks a lot for the quick response!  I wanted to actually test things out before commenting, and I think I've finally gotten everything to work great.  I'm actually using [esy](https://github.com/esy/esy) as the package manager and was momentarily blocked by it.  I did review the Dockerfiles as they were an excellent source of inspiration, so thank you for that! I'm happy to share the configuration that finally seems to be working for me.  Mostly leaving this here in case other people may need to stumble upon it in the future.

```json
{
  "dependencies": {
    "@opam/owl": "0.5.0"
  },
  "resolutions": {
    "@opam/conf-openblas": {
      "source": "link:./conf-openblas/opam",
      "override": {
        "exportedEnv": {
          "PKG_CONFIG_PATH": {
            "scope": "global",
            "val": "/opt/OpenBLAS/lib/pkgconfig:$PKG_CONFIG_PATH"
          },
          "LD_LIBRARY_PATH": {
            "scope": "global",
            "val": "/opt/OpenBLAS/lib:$LD_LIBRARY_PATH"
          }
        }
      }
    },
    "@opam/eigen": {
      "source": "git+ssh://git@github.com:owlbarn/eigen.git:eigen.opam#85cbb31",
      "override": {
        "buildEnvOverride": {
          "EIGENCPP_OPTFLAGS": "-Ofast -march=x86-64 -mfpmath=sse -funroll-loops -ffast-math",
          "EIGEN_FLAGS": "-O3 -Ofast -march=x86-64 -mfpmath=sse -funroll-loops -ffast-math"
        }
      }
    },
    "@opam/owl": {
      "source": "git+ssh://git@github.com:owlbarn/owl.git:owl.opam#8819213",
      "override": {
        "buildEnvOverride": {
          "OWL_CFLAGS": "-g -O3 -Ofast -march=x86-64 -mfpmath=sse -funroll-loops -ffast-math -DSFMT_MEXP=19937 -msse2 -fno-strict-aliasing -Wno-tautological-constant-out-of-range-compare",
          "OWL_AEOS_CFLAGS": "-g -O3 -Ofast -march=x86-64 -funroll-loops -ffast-math -DSFMT_MEXP=19937 -fno-strict-aliasing"
        }
      }
    }
  }
}
```

**Comment by mseri** [comment]
Thank you very much!

**Comment by mseri** [comment]
I am going to close the issue, but link to it from the README
