### ISSUE TITLE
[feature request] compare

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#40]
Here's a `compare` function written using `fold2` (see issue #39).  This can be used, for example, to allow matrices to be used with Jane Street's `Interval` module.
```ocaml
(** A compare function for matrices that returns zero if all elements of
    both matrices are equal, -1 if each element of the first is less
    than or equal to the corresponding element of the second, or 1 if
    each element of the first is greater than or equal to each element
    of the second.  Raises an exception otherwise. *)
let compare m1 m2 =
  let f acc e1 e2 =
    match acc with
         | -1 -> if e1 <= e2 then -1 else failwith "compare: incomparable"
         |  1 -> if e1 >= e2 then  1 else failwith "compare: incomparable"
         |  0 -> if e1 = e2 then 0
                 else if e1 < e2 then -1
                 else 1
         |  _ -> failwith "bug: acc is not -1, 0, or 1" (* avoid match warning *)
  in fold2 f 0 m1 m2
```
Treating a matrix as less than (greater than) another when every element is less than (greater than) or equal to corresponding elements is a choice.  Perhaps someone might want a function that treated matrices as incomparable if some pairs were less than (greater than) while others were equal.  Should there be two variants of `compare`?

**Comment by ryanrhymes** [comment]
Thanks for the code @mars0i , it looks nice, I will implement the `compare` function in the next release.

**Comment by mars0i** [comment]
Great--I'm happy if this and the `fold2` functions turn out to be useful.  

Here is one more function--a compare function for use with Markus Mottle's partially ordered map library [pomap](http://opam.ocaml.org/packages/pomap).  I'm not sure this belongs in owl, though.  The set of people who want to implement a partial order on matrices may be very small.

```ocaml
let pomap_compare m1 m2 =
  let f acc e1 e2 =
    match acc with
    | Equal -> if e1 < e2 then Lower else 
               if e1 > e2 then Greater else Equal
    | Lower ->   if e1 <= e2 then Lower else Unknown
    | Greater -> if e1 >= e2 then Greater else Unknown
    | Unknown -> Unknown (* should never happen given short circuit *)
  in Utils.short_circuit_fold2 Unknown f Equal m1 m2
```

After writing that, I felt that the code was organized in a way that made it easier to read than my original `Interval`-oriented `compare` function above.  Here's the original `compare` function rewritten in the same way:

```ocaml
let compare m1 m2 =
  let f acc e1 e2 =
    match acc with
         |  0 -> if e1 < e2 then -1 else
                 if e1 > e2 then 1 else 0
         | -1 -> if e1 <= e2 then -1 else failwith "incomparable"
         |  1 -> if e1 >= e2 then  1 else failwith "incomparable"
         |  _ -> failwith "bug: acc is not -1, 0, or 1" (* avoid match warning *)
  in Utils.fold2 f 0 m1 m2
```
