### ISSUE TITLE
of_array on sparse matrices is slow

### ISSUE THREAD

**Issue by bobpoekert** [owlbarn/owl#410]
of_array on sparse matrices currently calls insert on a loop:
https://github.com/owlbarn/owl/blob/c862c0741ceda37e160894254d93501fd50b5acc/src/owl/sparse/owl_sparse_matrix_generic.ml#L534-L538

this results in a lot of memory allocation and memcpy-ing if you're constructing a matrix with a lot of data in it. eigen has a way to fill a sparse matrix in batch (https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html#acc35051d698e3973f1de5b9b78dbe345). it would be nice if the of_array function used this method instead of inserting on a loop.

**Comment by jzstark** [comment]
Close due to the removal of sparse modules.
