### ISSUE TITLE
Segmentation fault when saving a dense matrix

### ISSUE THREAD

**Issue by clecat** [owlbarn/owl#422]
I have a dense matrix of 58320 by 11664:
```
        C0  C1  C2  C3  C4     C11659 C11660 C11661 C11662 C11663 
    R0 137 137 137 137 137 ...    255    255    255    255    255 
    R1 132 132 132 132 131 ...    255    255    255    255    255 
    R2 152 152 147 147 144 ...    160    161    159    159    160 
    R3 154 152 152 154 152 ...    155    159    162    162    156 
    R4  65  65  65  65  65 ...     80     65     66     67     83 
       ... ... ... ... ... ...    ...    ...    ...    ...    ... 
R58315 239 233 231 234 237 ...     94     93     93     96     96 
R58316 103 103 102 106 106 ...    255    255    255    255    255 
R58317  78  88  87  77  58 ...    231    226    231    238    244 
R58318   0   0   0   0   0 ...     32     38     35     33     33 
R58319   0   0   0   0   0 ...     32     22     22     41     50 
```
But when I try to save it using `Owl_dense_matrix.S.save`, the program crashes with a segmentation fault in a memcpy due to wrong alignment.

This function calls in reality Owl_io.marshal_to_file which uses a string before saving it into a file: [(owl/src/base/misc/owl_io.ml at line 113)](https://github.com/owlbarn/owl/blob/master/src/base/misc/owl_io.ml#L113)
```ocaml
let marshal_to_file x f =
  let s = Marshal.to_string x [] in
  let h = open_out f in
  output_string h s;
  close_out h
```
The crash happens during the call to `Marshal.to_string`, which calls the external function [`caml_output_value_to_string`](https://github.com/ocaml/ocaml/blob/trunk/runtime/extern.c#L749) calling itself [`caml_output_value_to_string`](https://github.com/ocaml/ocaml/blob/trunk/runtime/extern.c#L719).

I have no idea why, however, in the first time, calling `Marshal.to_channel` instead of using a string seems to solve the problem.
Indeed, I was able to save the value, load it later and use it normally:
```ocaml
let marshal_to_file x f =
  let h = open_out f in
  Marshal.to_channel h x [];
  close_out h
```

**Comment by mseri** [comment]
It's late and I am tired, so I hope to say something reasonable. The length parameter used for the string is a `long int` (https://github.com/ocaml/ocaml/blob/30f2cb1d81b1f257cce477d7b6dd7aa5867178cc/runtime/extern.c#L732). You have over 600 million numbers in your matrix, between the digits and commas and everything I think you may be overflowing the size there.

By using channel (that in any case should be also faster and less memory intensive, so worth changing imho -- ping @ryanrhymes) you batch update the channel and avoid computing any lenght.

**Comment by clecat** [comment]
I thought about an overflow of the size, but `Sys.max_string_length` gives me 144115188075855863 on my 64 bytes architecture, which is more than 144115188 gigabytes, so I'm not sure it's really the problem (my files after `Marhsal.to_channel` are about 2.7 gigabytes)

**Comment by mseri** [comment]
Yes but that is not the size of the allocated string buffer.

**Comment by ryanrhymes** [comment]
+1 @mseri agree, using channel is a better solution, can you PR whenever you are free?

**Comment by mseri** [comment]
@clecat, before saving the matrix, can you print `Marshal.data_size`, `Marshal.header_size` and `Marshal.total_size` for your matrix and see if they print the right values?

**Comment by mseri** [comment]
Creating the matrix with `Mat.create` everything works fine, using `Owl_dense_matrix.S.save` if fails

**Comment by mseri** [comment]
I still think we should understand why it fails though. I'll try to investigate it on the side

**Comment by mseri** [comment]
I have made a minimal repro and raised the bug on the ocaml issue tracker

**Comment by mseri** [comment]
Looks like it will be fixed soon: https://github.com/ocaml/ocaml/pull/8788

**Comment by clecat** [comment]
Nice, thx for all the work
