### ISSUE TITLE
super odd bug in `exponential_rvs`

### ISSUE THREAD

**Issue by ghennequin** [owlbarn/owl#426]
Super weird:
```
let exp_rv = Owl_stats.exponential_rvs
Mat.init 1000000 1 (fun _ -> exp_rv 1.0) |> Mat.mean'
```
consistently returns ~1.03 (very, very significantly above 1.0).
In contrast, hand-coding the draw from the exp. distribution, using the SAME CODE as in [the owl source code](https://github.com/owlbarn/owl/blob/master/src/base/stats/owl_base_stats_dist_exponential.ml), i.e:
```
let exp_rv lambda =
  let u = Random.float 1.0 in
  let s = -1. /. lambda in
  s *. log1p (-.u)

Mat.init 1000000 1 (fun _ -> exp_rv 1.0) |> Mat.mean'
```
returns 1.000 as it should. WTH :) Any idea?

**Comment by tachukao** [comment]
bug seems to be somewhere inside the definition of `std_exponential_rvs` here
https://github.com/owlbarn/owl/blob/a60b6b838902300a11172e4376aac79ded44fcea/src/owl/stats/owl_stats_ziggurat.c#L15
any ideas @ryanrhymes ?
