### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by pveber** [owlbarn/owl#443]
On this [page](https://ocaml.xyz/chapter/algodiff.html#example-2-gradient-descent-algorithm), the link to `owl_algodiff_generic.mli` is broken.

**Comment by ryanrhymes** [comment]
Thanks for reporting this. Calvin @tachukao has been improving algodiff and there are some restructing in the code base. Also we are preparing new tutorial book, so two parts are not well synced at the moment.

I will try to migrate the old content to the new tutorial tooling asap, then start writing a new one atop of it.

**Comment by tachukao** [comment]
@ryanrhymes after moving the doc strings to above in `owl_algodiff_generic.mli`, does it work now with owl_doc?

**Comment by ryanrhymes** [comment]
It shouldn't work, because owl_doc only read the doc blow the type signature. I haven't try to rebuild the document yet. I am leaning to use standard ocaml doc tool in future. There are pros and cons but definitely reduces my overhead of maintaining another separate tool.

**Comment by tachukao** [comment]
@ryanrhymes sorry I mean after moving the doc strings to below in `owl_algodiff_generic_sig.ml`, this was done in the latest PR

**Comment by ryanrhymes** [comment]
Haha, I was also confused ... then it should certainly work. I will try to rebuild the whole doc during the weekend.

**Comment by ryanrhymes** [comment]
Tutorial book is working in process now, imo it is a safe assumption it will show up at ocaml.xyz at some point. I will close this for now.
