### ISSUE TITLE
owl-top failed on macOS: string.h not found

### ISSUE THREAD

**Issue by vietlq** [owlbarn/owl#445]
Specifically on macOS Mojave I needed to run:

https://stackoverflow.com/a/55465527/128028

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

Please update documentation so people using macOS can benefit from it. After installing the package above, I could install `owl-top` without issues.

**Comment by ryanrhymes** [comment]
I will find somewhere to mention this, but it does not seem like owl specific issues.
