### ISSUE TITLE
Plot.ecdf goes into the infinite loop

### ISSUE THREAD

**Issue by zbroyar** [owlbarn/owl#459]
Hi,

Looks like Plot.ecdf love its work so much that it can run forever :-)
The following code snippet says that "subplot 0 0 is out" and hangs while eating 100% of CPU.

```
let plot_histogram basename a =
  let open Owl_plplot in
  let stt = calculate_vector_stats a in
  let fn = sprintf "%s-%f-%f.ps" basename stt.min stt.max in
  let m = Mat.of_array a (A.length a) 1 in
  let h = Plot.create ~m:2 ~n:1 fn in
  Plot.(subplot h 0 0; histogram ~h ~bin:200 m);
  printf "I: plot_histogram: subplot 0 0 is out\n%!";
  Plot.(subplot h 1 0; ecdf ~h m);
  printf "I: plot_histogram: subplot 1 0 is out\n%!";
  Plot.output h;
```

[gdbprofiler](https://github.com/copy/gdbprofiler) says the process spend most of its time (after entering Plot.ecdf) in __memmove_sse2_unaligned_erms. GitHub doesn't allow me to attach out.cpuprofile, so please see screenshots below:

<img width="715" alt="Screenshot 2019-11-22 at 14 48 45" src="https://user-images.githubusercontent.com/338701/69427151-9907a980-0d37-11ea-94cc-164c83934749.png">

<img width="753" alt="Screenshot 2019-11-22 at 14 49 09" src="https://user-images.githubusercontent.com/338701/69427168-a329a800-0d37-11ea-97e2-fa602cf3f2ac.png">

**Comment by jzstark** [comment]
So here is a simple script I've tried:

```ocaml
open Owl_plplot

let x = Dense.Ndarray.D.(uniform [|100|]);;
let x' = Dense.Ndarray.D.to_array x;;
let a, b = Stats.ecdf x';;

let h = Plot.create "test.png";;
let _ = Plot.ecdf ~h x;;
let _ = Plot.output h;;
```
Both  `Stats.ecdf` and `Plot.ecdf` work as expected. So perhaps the issue is related with specific input data used, e.g. a very large ndarray?

**Comment by ryanrhymes** [comment]
@jzstark thank you jianxin, feel free to remove the bug tag if it is certain that this is not a bug.

**Comment by zbroyar** [comment]
@jzstark, the size of the array is pretty moderate: 22716 elements. What is the O-complexity of Stats.ecdf?

**Comment by zbroyar** [comment]
@jzstark, please, ignore my previous question.

I found the problem: Stats.ecdf goes into infinity if there is at least one NaN among the values of the input array.

**Comment by zbroyar** [comment]
Hey, friendly bump here.
Will this be fixed any time soon or noted in the documentation?

**Comment by mseri** [comment]
Added to the bulk fix PR: https://github.com/owlbarn/owl/pull/534
