### ISSUE TITLE
stats_rv test failure with Clang

### ISSUE THREAD

**Issue by bcdarwin** [owlbarn/owl#462]
This is perhaps not a 'fair' issue since Clang isn't supported by the Eigen bindings (https://github.com/owlbarn/eigen/issues/1), but despite this I was able to compile with the Clang in Nix-unstable on Darwin simply by replacing `g++` with `$(CXX)` in `eigen_cpp/lib/Makefile` in that package (https://github.com/owlbarn/owl/issues/460).  However, this results in a test failure in `stats_rvs.044`:

```
cauchy_loc_-1.000000_scale_3.000000: Avg sq diff in cdf 1.2644e-09 pdf 3.37942e-05 max cdf 1.06625e-07 pdf 0.00258429
         Avg err logcdf 0 logpdf 0 ppf 1.76687e-33 isf 1.83486e-28
         Avg err sf 0 logsf 0
[failure] Error Avg isf error in 'cauchy_loc_-1.000000_scale_3.000000' <1E-28: expecting
true, got
false.
```

**Comment by mseri** [comment]
Can you please send a PR to `eigen` to change g+c to $(CXX)? The error may just be numerical instability, does it fail consistently?

**Comment by bcdarwin** [comment]
On Linux with GCC it doesn't fail.  Using Clang it consistently fails but with a fairly small error (~ 1e-28 - 3e-28).

**Comment by mseri** [comment]
Thanks. @tachukao if you are looking at tests failures, it may be worth to take also this into account

**Comment by mseri** [comment]
I think this is now fixed as well. Please reopen it if I am wrong

**Comment by bcdarwin** [comment]
Still failing in the above manner with Clang.

**Comment by bcdarwin** [comment]
I can't reopen but feel free to do so if you like.

**Comment by mseri** [comment]
@bcdarwin we are updating again the way eigen is built. Can you check if owl builds in your setting with eigen from git://github.com/nandor/eigen.git ?

**Comment by bcdarwin** [comment]
Switching to Dune 2.0.0 is still a WIP in Nixpkgs.  I'm able to build using Linux/gcc but not OSX/Clang but it's seemingly an issue with finding the C++ stdlib which might be related to the generic Nix builders rather than Eigen itself.

**Comment by bcdarwin** [comment]
There are some obvious issues like use of `-ansi` in eigen_cpp/dune but more generally the issue is that the compiler options are semi-hard-coded (i.e. not easy to override individually) as per https://github.com/owlbarn/owl/issues/464 .

**Comment by mseri** [comment]
I am happy to make all the hard coded flags that can cause problem configurable via custom flags, with the dune 2 changes it will be much easier to do in eigen, and probably we can simplify owl as well.

Meanwhile will the released 0.1.5 be good for you until nix can move to dune2?

**Comment by bcdarwin** [comment]
Excellent, thanks!

(My main setup is Linux, but was just testing on OSX.  0.1.5 compiles on the latter and seems to work fine - I just had to disable the Owl test suite.)

**Comment by mseri** [comment]
Thanks. I hope we can also figure out the reason of that failure and close this issue as well

**Comment by mseri** [comment]
I wonder if the error on such small margin is meaningful, would it make sense to update the bound to `E-27` or `5E-28`?
