### ISSUE TITLE
Build configuration

### ISSUE THREAD

**Issue by bcdarwin** [owlbarn/owl#464]
Eigen and Owl fail to build with compilers that don't support SSE instructions without setting certain environment variables (EIGEN_FLAGS, etc.).

**Comment by jzstark** [comment]
Thanks for reporting this issue. Would you please help to post some more details about error information?

**Comment by bcdarwin** [comment]
See [here](https://github.com/NixOS/nixpkgs/pull/74274#issuecomment-559369628).

**Comment by jzstark** [comment]
Ah, I see. [Here](https://github.com/owlbarn/owl/blob/master/docker/Dockerfile.ubuntu.arm) is an old Dockerfile we used to install Owl on rPi, and might be of help. Indeed there are several flags to be changed. Improvement on the configuration system is still required.

**Comment by mseri** [comment]
We have added the special flags and documented them in the readme for this reason. The optimisation did make a difference in our tests, but if you find that some of them are no longer necessary and increase the number of platforms supported out of the box, feel free to send us a PR to relax them.

Given that this is solved by tweaking the flags for the various systems, I am going to close the issue
