### ISSUE TITLE
Failed to install Owl on Ubuntu using Dockerfile.ubuntu as the example.

### ISSUE THREAD

**Issue by dborisog** [owlbarn/owl#482]
I failed to install Owl on Ubuntu 18.04 (ocaml-base-compiler.4.07.1) using instructions from Dockerfile.ubuntu. Please have a look at the list of commands below followed by the error message.

1. git clone https://github.com/xianyi/OpenBLAS.git
2. in OpenBlass directory: make, make instal, ldconfig /opt/OpenBLAS/lib
3. DEBIAN_FRONTEND noninteractive, apt-get update -y  (and the rest of the prerequisites section.
4. export OWL_DISABLE_LAPACKE_LINKING_FLAG=1
5. export OWL_COMPILE_CFLAGS="-I/opt/OpenBLAS/include -I/home/dborisog/projects/OpenBLAS/lapack-netlib/LAPACKE/include/ -L/opt/OpenBLAS/lib"
6. CFLAGS=${OWL_COMPILE_CFLAGS} opam install owl owl-top owl-plplot utop -y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of owl-zoo failed at "/home/dborisog/.opam/opam-init/hooks/sandbox.sh build dune build -p owl-zoo -j 7".

=== ERROR while compiling owl-zoo.0.7.2 ======================================#
context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#8c72aed0
path        ~/.opam/4.07.1/.opam-switch/build/owl-zoo.0.7.2
command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p owl-zoo -j 7
exit-code   1
env-file    ~/.opam/log/owl-zoo-10226-d0f245.env
output-file ~/.opam/log/owl-zoo-10226-d0f245.out
### output ###
[...]
/home/dborisog/.opam/4.07.1/.opam-switch/build/owl.0.7.2/_build/default/src/owl/src/owl/lapacke/owl_lapacke_generated_stub.c:37725: undefined reference to `LAPACKE_zhetrf_rook'
/home/dborisog/.opam/4.07.1/lib/owl/libowl_stubs.a(owl_lapacke_generated_stub.o): In function `owl_stub_1031_LAPACKE_chetrs_rook':
/home/dborisog/.opam/4.07.1/.opam-switch/build/owl.0.7.2/_build/default/src/owl/src/owl/lapacke/owl_lapacke_generated_stub.c:37756: undefined reference to `LAPACKE_chetrs_rook'
/home/dborisog/.opam/4.07.1/lib/owl/libowl_stubs.a(owl_lapacke_generated_stub.o): In function `owl_stub_1032_LAPACKE_zhetrs_rook':
/home/dborisog/.opam/4.07.1/.opam-switch/build/owl.0.7.2/_build/default/src/owl/src/owl/lapacke/owl_lapacke_generated_stub.c:37792: undefined reference to `LAPACKE_zhetrs_rook'
/home/dborisog/.opam/4.07.1/lib/owl/libowl_stubs.a(owl_lapacke_generated_stub.o): In function `owl_stub_1033_LAPACKE_csyr':
/home/dborisog/.opam/4.07.1/.opam-switch/build/owl.0.7.2/_build/default/src/owl/src/owl/lapacke/owl_lapacke_generated_stub.c:37825: undefined reference to `LAPACKE_csyr'
/home/dborisog/.opam/4.07.1/lib/owl/libowl_stubs.a(owl_lapacke_generated_stub.o): In function `owl_stub_1034_LAPACKE_zsyr':
/home/dborisog/.opam/4.07.1/.opam-switch/build/owl.0.7.2/_build/default/src/owl/src/owl/lapacke/owl_lapacke_generated_stub.c:37856: undefined reference to `LAPACKE_zsyr'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build owl-zoo 0.7.2
└─ 
╶─ No changes have been performed

Are there any actions I missed or made mistakes?

**Comment by mseri** [comment]
sorry for the latency. I am surprised, as it works fine in docker. 

In my system I compile by only setting `PKG_CONFIG_FLAGS=“ /opt/OpenBlas/lib/pkgconfig”` (the folder of openblas.pc) instead of touching the linking flags manually, can you check if this solves your issue?

**Comment by dborisog** [comment]
0.0. rm -rf OpenBLAS

1.0. git clone https://github.com/xianyi/OpenBLAS.git
1.1. cd OpenBLAS
1.2. make
1.3. sudo make install   #openblas.ps in /opt/OpenBLAS/lib/pgconfig
1.4. sudo ldconfig /opt/OpenBLAS/lib/

2.0. export DEBIAN_FRONTEND="noninteractive"
2.1. sudo apt-get update -y
2.2. apt-get install -y m4 wget unzip aspcud libshp-dev libplplot-dev gfortran pkg-config git
2.3. opam update -q
2.4. opam upgrade

3.0. export PKG_CONFIG_FLAGS="/opt/OpenBLAS/lib/pkgconfig/"
3.1. opam install owl owl-top owl-plplot utop -y

Unfortunately, I receive the same message, with and without OWL_DISABLE_LAPACKE_LINKING_FLAG and CFLAGS=${PKG_CONFIG_FLAGS} or  CFLAGS=${OWL_COMPILE_CFLAGS}

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build owl-zoo 0.7.2
└─ 
╶─ No changes have been performed

**Comment by mseri** [comment]
@dborisog I use the same procedure listed above, but I only just realised that I had also added `/opt/OpenBLAS/lib` to `/etc/ld.so.conf`. To see if this may be the culprit can you do:
```
3.0. PKG_CONFIG_FLAGS="/opt/OpenBLAS/lib/pkgconfig/" \
LD_LIBRARY_PATH="/opt/OpenBLAS/lib:$LD_LIBRARY_PATH" \
LD_RUN_PATH="/opt/OpenBLAS/lib:$LD_RUN_PATH" \
opam install owl owl-top owl-plplot utop -y
# In this way the path are set only temporarily for the invocation of opam and you can check if it succeeds
```

**Comment by dborisog** [comment]
@mseri , I'm sorry for a delayed reply to such a simple thing to check, at this moment I have an attention span of a goldfish for the most things excluding a very limited number of topics. 

Unfortunately, the command produced the same (or very similar, as instead of "LAPACKE_zsyr" I have "LAPACKE_zsyr" on the last line of) error message. 

I'm not installing it to a clean Ubuntu (I expect the same for you), thus I do not exclude some unorthodox specifics in installs or configs, and having the goldfish-alike brain does not produce a sufficient willpower to use VMWare for testing on a virtual machine, especially as I already solved the programming task by a custom code. Thus, the only positive thing in this comment is a bit of humor.   )

**Comment by mseri** [comment]
We have been notified that the standard plain install should work on the latest Ubuntu release
