### ISSUE TITLE
Slicing node in Neural.Graph

### ISSUE THREAD

**Issue by mreppen** [owlbarn/owl#483]
I need to slice my input and feed the slices separately into the next step in my network. I could not find any interface to do the slicing, and
```
let open Owl.Neural.S in
Graph.(input [| 10; 10 |]
|> lambda (fun x -> Algodiff.Maths.get_slice [[1]] x))
```
yields
```
...
[ Node lambda_1 ]:
    Lambda       : in:[*,10,10] out:[*,10,10]
    customised f : t -> t
    prev:[input_0] next:[]
...
```
but the out dimension should be `1 x 10`.

Am I missing something?

**Comment by jzstark** [comment]
Thanks a lot for reporting this issue. The input and output shape of the lambda layer is the same by design, whatever math operations are used inside this layer. That's because we need to perform static shape checking, but the real output shape of lambda layer cannot be known until runtime. Instead of changing the basic design of the neural network module, I suggest adding a new "slice" neuron if necessary, though I'm still not quite clear about if this task can be achieved by simply pre-processing the input data before feeding them into a neural network.

**Comment by mreppen** [comment]
A slice neuron would be great. I imagine pre-processing could achieve it in many cases, but at least in mine it is more natural to do it in the network.

Tensorflow has both `slice` and `split`, which would both be useful.
https://www.tensorflow.org/api_docs/python/tf/slice
https://www.tensorflow.org/api_docs/python/tf/split

Another option would be another lambda layer (optional argument?) where the user can specify the output shape. That would cover all cases, even the more complicated ones with both slicing and computations. This is available in tensorflow/Keras: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Lambda

Personally, I would like all of these options.

**Comment by mreppen** [comment]
The following gets the job done
```
let open Owl.Neural.S in
let open Graph in
let inp = input [| 10; 10 |] in
lambda_array [|10; 1|] (fun x -> Algodiff.Maths.(get_slice [[]; []; [1]] (Array.get x 0))) [|inp|]
```

The other functions would still make it much prettier though. Maybe I can have a look at making a real neuron this weekend.

**Comment by jzstark** [comment]
I've just made a PR so that a lambda layer can have an optional  parameter for specifying output shape: https://github.com/owlbarn/owl/pull/485.

**Comment by mreppen** [comment]
That looks great. I am having trouble compiling the master branch (also before the PR), but will try it out when it compiles.

I will leave the issue open for the case that `slice` and/or `split` will be implemented, but if there is no such plan, feel free to close.

**Comment by ryanrhymes** [comment]
@mreppen you might be also interested in owl symbolic https://github.com/owlbarn/owl_symbolic/blob/master/example/example_14.ml

**Comment by mreppen** [comment]
@ryanrhymes Thanks. What I understand looks cool!

PS. Just finished a working version of my first Owl project (what lead to this issue).

**Comment by mreppen** [comment]
@jzstark @ryanrhymes 
I implemented a slice node: https://github.com/owlbarn/owl/commit/c24eb60293736b330f0e292e6e50627540b3371a

Most code is just for computing the new output shape.

Would it make sense to make a PR out of this?

**Comment by ryanrhymes** [comment]
@mreppen yes, please go ahead and PR. @jzstark and @tachukao and I can have a look and comment.
