### ISSUE TITLE
Arr print shape

### ISSUE THREAD

**Issue by tachukao** [owlbarn/owl#492]
A function that prints the shape of an N-dimensional array would be super useful
e.g.

```
let print_shape ?label x =
  let s = Arr.shape x |> Array.map string_of_int |> Array.to_list |> String.concat ", " in
  match label with
  | None ->  Printf.printf  "shape: (%s)\n%!" s
  | Some z -> Printf.printf "[%s] shape: (%s)\n%!" z s
```

**Comment by ryanrhymes** [comment]
ok, i can add ... another note, you may find this function useful as well https://github.com/owlbarn/owl/blob/5d652b10add0f9c31395e358f18b5180a8a7ecec/src/base/misc/owl_utils_array.mli#L347

**Comment by tachukao** [comment]
thanks and no worries, I can add this the s.e.m. functions later myself, just thought I would leave a note in case I forget
