### ISSUE TITLE
set_{x,y,z}ticklabels ignored in 3D plots

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#50]
`set_xticklabels`, `set_yticklabels`, and `set_zticklabels` don't seem to work in 3D plots.  The first two do seem to work in 2D plots:
```OCaml
let f x = Maths.sin x /. x in
let h = Plot.create "foo2d.pdf" in
Plot.set_xticklabels h [(8., "eight")];
Plot.plot_fun ~h f 1. 15.;
Plot.output h
```
but not in 3D plots:
```OCaml
let x, y = Mat.meshgrid (-2.5) 2.5 (-2.5) 2.5 100 100 in
let z0 = Mat.(sin ((pow1 x 2.) + (pow1 y 2.))) in
let h = Plot.create "foo3d.pdf" in
Plot.set_yticklabels h [(0., "zero")];
Plot.surf ~h x y z0;
Plot.output h
``` 
The *y* border is front right, and I would expect the "0" in the middle of that edge to be replaced by "zero", but the "0" remains (and no other axis is affected).

Thanks again-

Marshall

**Comment by mars0i** [comment]
Maybe this has to do with this line being in the 2D section of `_prepare_page`
```OCaml
 let _ = pllab p.xlabel p.ylabel p.title in ()
```
with nothing analogous in the 3D section?

**Comment by ryanrhymes** [comment]
Yes, this is a known bug and I haven't really figured it out where the problem comes from. I will take a look later this week when I have bit more time. Many thanks for the suggestion as always.
