### ISSUE TITLE
Feature request: Ndarray stack

### ISSUE THREAD

**Issue by tachukao** [owlbarn/owl#505]
It would be useful to have a function `stack` in the Ndarray module similar to the `stack` function in numpy:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html#numpy.stack

To achieve the same functionality right now we have to first expand the dimensions of the ndarrays and concatenate along that axis. The proposed function would have type signature

```ocaml
val stack : ?axis:int -> arr array -> arr
```

A naive implementation would be

```ocaml
let stack ?(axis = 0) xs =
      let shp = Arr.shape xs.(0) in
      let ndim = Array.length shp + 1 in
      let axis = Owl_utils.adjust_index axis ndim in
      let new_shp = Array.init ndim (fun i ->
             if i < axis then shp.(i)
             else if i = axis then 1
             else  shp.(i-1)) in
      let y = Array.map (fun x ->
                   let shp' = Arr.shape x in
                   if shp' <> shp then failwith "stack: ndarrays in [xs] must all have the same shape";
                   Arr.reshape x new_shp) xs in
       Arr.concatenate ~axis y
```

**Comment by ryanrhymes** [comment]
The naive impl looks fine by me, for large ndarray, most of the time will be spent in concatenate function anyway.
