### ISSUE TITLE
MNIST Example Clarification

### ISSUE THREAD

**Issue by smolck** [owlbarn/owl#507]
Hello! I have a question concerning [the MNIST CNN example](https://github.com/owlbarn/owl/blob/master/examples/mnist_cnn.ml). In that example, there is this line:

https://github.com/owlbarn/owl/blob/b0e6e735863af52e945aaa286fcbe21ffefad8e0/examples/mnist_cnn.ml#L16

I'm wondering why that layer has 1024 inputs? After looking at these lines:

https://github.com/owlbarn/owl/blob/b0e6e735863af52e945aaa286fcbe21ffefad8e0/examples/mnist_cnn.ml#L13-L14

and reading some of Owl's source code it appears that the conv layer has a kernel of size 5x5, with 1 input feature, 32 output features, and a 1x1 stride. By the same reasoning, it seems that the max_pool2d layer has a kernel of size 2x2 and a 2x2 stride. However, after doing some calculations using the formula `((W - K + 2p) / S) + 1` (see https://en.wikipedia.org/wiki/Convolutional_neural_network#Spatial_arrangement) I came up with the output from the max_pool2d layer being 12x12, but that doesn't explain why [the fully connected layer mentioned previously](https://github.com/owlbarn/owl/blob/b0e6e735863af52e945aaa286fcbe21ffefad8e0/examples/mnist_cnn.ml#L16) has 1024 inputs.

Forgive me if this is a misunderstanding of CNN's in general, and not of Owl, as I'm new to CNN's. Though there doesn't appear to be any documentation on what the arguments to `conv2d`, `max_pool2d` and other similar functions mean anyway, and `conv2d [5;5;1;32] [1;1]` is pretty ambiguous, at least for me, so that makes things even more difficult. Would you mind explaining what `[5;5;1;32]` and `[1;1]` mean? I've gathered that the 5's are the kernel size, the 1 is the input features, and the 32 is the output features, with the `[1;1]` being the stride. Am I right here?

Thanks in advance!

**Comment by jzstark** [comment]
Hi, thanks for investigating DNN with Owl! You understanding of the interface of `conv2d` is correct. It's `[kernel_col, kernel_row, input channel, output channel]` and `[stride_col, stride_row]`.  

As to the `1024`, it specifies the output dimensionality of the `fully-connected` layer, and has nothing to do with input size. You can change it to `512` and the network would still work.  

By the way, the output size of the `max_pool2d` layer is `[*, 14,14,32]`. The shape calculation with SAME padding is a bit tricky.  You can observe the output shape of each layer with `Graph.print network`.

**Comment by smolck** [comment]
> Hi, thanks for investigating DNN with Owl! You understanding of the interface of `conv2d` is correct. It's `[kernel_col, kernel_row, input channel, output channel]` and `[stride_col, stride_row]`.

Great, thanks! Where is this documentation found? I looked at https://ocaml.xyz/owl/owl/Owl_neural/S/Graph/index.html#val-conv2d, but it isn't there.

> As to the `1024`, it specifies the output dimensionality of the `fully-connected` layer, and has nothing to do with input size. You can change it to `512` and the network would still work.

Ah, I see. That makes more sense! So are the input dimensions automatically calculated based on how the layers are defined?

> By the way, the output size of the `max_pool2d` layer is `[*, 14,14,32]`. The shape calculation with SAME padding is a bit tricky. You can observe the output shape of each layer with `Graph.print network`.

Thanks a lot! I wondered if there was some padding in there.

**Comment by jzstark** [comment]
Currently we don't have systematic documents on the interfaces of DNN operators.  The input dimensions are automatically calculated so the input shape is only specified at the beginning. If you look at the source code in `owl_neural_neuron.ml`, compared with `linear`, the `fully _connected` layer has an extra `reshape` operation that turns the input tensor into a matrix before the matrix multiplication step.

**Comment by smolck** [comment]
> Currently we don't have systematic documents on the interfaces of DNN operators. 

I'm happy to help with this wherever I can, just let me know ;)

> The input dimensions are automatically calculated so the input shape is only specified at the beginning. 

That's nice! Less to think about, compared to, for example, PyTorch where you have to specify that manually.

> If you look at the source code in `owl_neural_neuron.ml`, compared with `linear`, the `fully _connected` layer has an extra `reshape` operation that turns the input tensor into a matrix before the matrix multiplication step.

What are the implications of that extra step? Better performance?

**Comment by jzstark** [comment]
I think the extra step is mainly for the efficiency of coding, otherwise the users need to manually reshape the input before using a linear layer.

**Comment by smolck** [comment]
Okay, makes sense. Thank you very much for all of your help! Now that I understand the syntax and what's going on, I think I'll be using Owl for learning and using NN's instead of PyTorch!
