### ISSUE TITLE
Generic.map doesn't work

### ISSUE THREAD

**Issue by roddyyaga** [owlbarn/owl#514]
When I do
```ocaml
let a = Generic.create Bigarray.Int [| 2; 3 |] (4) in
Generic.map (fun n -> n + 1) a
```
I get `Exception: Failure "_owl_copy: unsupported operation"`. Am I doing something wrong?

**Comment by ryanrhymes** [comment]
The support for integers are actually well implmented already in Owl's core, check the link below ...

https://github.com/owlbarn/owl/blob/45d9b80cef5b1fe9c5dfa20264b3aa607cbe0908/src/owl/core/owl_ndarray_maths_stub.c#L3669

They are also interfaced in OCaml part already, as you see with the link below ...

https://github.com/owlbarn/owl/blob/45d9b80cef5b1fe9c5dfa20264b3aa607cbe0908/src/owl/core/owl_ndarray_maths.ml#L5118

This should work ...

```ocaml
let a = Generic.create Bigarray.Int32 [| 2; 3 |] 4l in
Generic.map (fun n -> Int32.add n 1l) a;;
```

**Comment by roddyyaga** [comment]
Thanks! Is the list of types that `Generic` supports listed anywhere?
