### ISSUE TITLE
Exception when transposing an integer matrix

### ISSUE THREAD

**Issue by jonathan-laurent** [owlbarn/owl#523]
When executing this snippet:
```ocaml
open Owl;;
open Owl.Dense.Ndarray.Generic;;
transpose (create Bigarray.int [|3;4|] 2)
```
I get the following exception:
```
Exception: Failure "_matrix_transpose: unsupported operation".
```

**Edit:** it seems that many other tensor operations are not available for integer tensors. Another example is `get_fancy`.

**Comment by jzstark** [comment]
Yes. Many ndarray operations such as `transpose` are interfaced to the core C code. Currently most core operations support input of float and complex types, but not integer type.

**Comment by mseri** [comment]
We need to fix this, as the function is provided by the `base` library. 
The following should work

```ocaml
 open Owl_base_dense_ndarray_generic
transpose (create Bigarray.int [|3;4|] 2)
```

**Comment by jzstark** [comment]
Currently the integer type is still not supported in Owl. The basic type system in Owl remain a core pillar in its design; adding another new type such as integer and Float16 requires a lot of coding effort and significant change. Currently it is still suggested to use the float32 or float64 type.
