### ISSUE TITLE
Is there multiple linear regression in Owl?

### ISSUE THREAD

**Issue by UnixJunkie** [owlbarn/owl#541]
If not, then you can consider this as a feature request.

PS: https://www.investopedia.com/terms/m/mlr.asp
and https://en.wikipedia.org/wiki/Theil%E2%80%93Sen_estimator

**Comment by jzstark** [comment]
The multiple linear regression is supported in Owl; an example is shown in the [regression chapter](https://ocaml.xyz/book/regression.html) in our Owl book.

**Comment by UnixJunkie** [comment]
ok, sorry
