### ISSUE TITLE
Linking error on Windows

### ISSUE THREAD

**Issue by kkirstein** [owlbarn/owl#548]
First of all, sorry, if this is the wrong project, but I am not sure whether this issue is caused by `eigen` or `owl` itself.

I started an attempt to install `owl` on Windows by using [OCaml for Windows](https://fdopen.github.io/opam-repository-mingw/), which is a Cygwin environment for compiling to native Windows by mingw. After patching `conf-openblas` (adding the correct C-compiler to its `opam` file) and `owl` (`posix_memalign` is not available in mingw), I managed to install `owl` (via `opam`) and basic features seem to work. But as soon, as `eigen` functions are used, I get linking errors of multiple definitions of some C++ stdlib symbols. For instance, this happens, when installing `owl-zoo` or calling `dune runtest` for the `owl` project:

```
$ opam install owl-zoo
The following actions will be performed:
  ∗ install owl-zoo 0.10.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[owl-zoo.0.10.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of owl-zoo failed at
        "C:\\Opt\\OCaml64\\home\\kayuwekirstein\\.opam\\4.11.1+mingw64\\bin\\dune.exe build -p
        owl-zoo -j 3".

#=== ERROR while compiling owl-zoo.0.10.0 =====================================#
# context     2.0.5 | win32/x86_64 | ocaml-variants.4.11.1+mingw64 | git+https://github.com/kkirstein/opam-repository-mingw.git#opam2
# path        ~/.opam/4.11.1+mingw64/.opam-switch/build/owl-zoo.0.10.0
# command     C:\Opt\OCaml64\home\kayuwekirstein\.opam\4.11.1+mingw64\bin\dune.exe build -p owl-zoo -j 3
# exit-code   1
# env-file    ~/.opam/log/owl-zoo-9456-42bb52.env
# output-file ~/.opam/log/owl-zoo-9456-42bb52.out
### output ###
#     ocamlopt bin/owl_bin_viz.exe (exit 2)
# (cd _build/default && C:\Opt\OCaml64\home\kayuwekirstein\.opam\4.11.1+mingw64\bin\ocamlopt.opt.exe -w -40 -g -o bin/owl_bin_viz.exe C:/Opt/OCaml64/home/kayuwekirstein/.opam/4.11.1+mingw64/lib/ocaml\unix.cmxa -I C:/Opt/OCaml64/home/kayuwekirstein/.opam/4.11.1+mingw64/lib/ocaml C:/Opt/OCaml64/home/kayuwekirstein/.opam/4.11.1+mingw64/lib/ocaml\bigarray.cmxa -I C:/Opt/OCaml64/home/kayuwekirstein/[...]
# /usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: C:\Opt\OCaml64\home\kayuwekirstein\.opam\4.11.1+mingw64\lib\eigen\cpp\libeigen_cpp_stubs_stubs.a(eigen_dsmat.o): in function `std::ctype<char>::do_widen(char) const':
# /usr/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/locale_facets.h:1084: multiple definition of `std::ctype<char>::do_widen(char) const'; C:/Opt/OCaml64/lib/gcc/x86_64-w64-mingw32/9.2.0/libstdc++.dll.a(d000605.o):(.text+0x0): first defined here
# /usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: C:\Opt\OCaml64\home\kayuwekirstein\.opam\4.11.1+mingw64\lib\eigen\cpp\libeigen_cpp_stubs_stubs.a(eigen_dsmat.o): in function `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf()':
# /usr/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/sstream:65: multiple definition of `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf()'; C:/Opt/OCaml64/lib/gcc/x86_64-w64-mingw32/9.2.0/libstdc++.dll.a(d004042.o):(.text+0x0): first defined here
# collect2: error: ld returned 1 exit status
# ** Fatal error: Error during linking
#
# File "caml_startup", line 1:
# Error: Error during linking (exit code 2)



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build owl-zoo 0.10.0
└─
╶─ No changes have been performed
```

My first idea was that during installation `eigen` picked-up the wrong libstdc++, e.g., the Cygwin one instead of Mingw, but I checked `dlleigen_stubs.dll` and `dlleigen_cpp_stubs_stubs.dll` with `ldd` and they refer to the correct ones. So, it might be an unfortunate mixture of static and dynamic linking...

I understand, if Windows is not a high prio target, but maybe someone ran into similar issues before and can give some advice.

**Comment by mseri** [comment]
I would like to understand why it happens but I would not know where to start, I don't have a windows machine or experience with mingw.
The type of error seems more related to an issue in the libraries provided by mingw, as if some header is included twice.
Or maybe we need som `ifdef MINGW` around in eigen's sources or the bindings.

Ideally, we should push for the development of https://github.com/owlbarn/owl_suitesparse to replace the use of `eigen` and ditch C++ from the build.

**Comment by kkirstein** [comment]
Thanks, for the feedback. I will play around with includes and linking flags of `eigen` and let you know, if I find something.

**Comment by jzstark** [comment]
Indeed it looks like an eigen problem. Sorry that we haven't explored the installation on Windows yet, and even in Linux the eigen issue during installation is sometimes tricky. Some previous issues might be remotely of help, such as #338 and #430 etc.

**Comment by kkirstein** [comment]
I think, I found it: Removing `-lstdc++` from the linking command for the C-stubs seems to fix the issue (see [here](https://github.com/kkirstein/eigen/commit/dac3ad6c9eb1246f5b01e26f0c5239484d24ee9e) ). I am planning to submit PRs for _Owl on Windows_, but would like to do more testing before.

**Comment by mseri** [comment]
Oh interesting, it used to fail on linux without that. Let's hope we don't need to add it conditionally :D

**Comment by kkirstein** [comment]
First tests show that `eigen` still compiles/installs on Linux (Ubuntu 20.04 on WSL2) without `-lstdc++` for the c-stubs lib.

**Comment by mseri** [comment]
Super! If you send me a Pr on eigen repository I can draft a release and make a large scale test using the opam-repository revdeps ci
