### ISSUE TITLE
[win32] Owl_maths.mulmod fails on large inputs

### ISSUE THREAD

**Issue by kkirstein** [owlbarn/owl#550]
On Windows `Owl_maths.mulmod` fails on large input numbers, e.g., close to `max_int`. Here is an excerpt of the respective unit test (run in `utop`):
```
#require "owl";;
let i = max_int;;
Owl_maths.mulmod (i-1) (i-1) 0;;
```
This should return `0`, but runs forever (probably hangs in the `while` loop of the respective C-code). Maybe it's an issue with integer bit size. Investigation is ongoing...

**Comment by kkirstein** [comment]
I probably found the reason. Due to the history of `mingw32` (hence the name), on Windows `long` is 32 bits wide, while in the code it is expected to be 64 bits. Actually, now I am surprised, it only crashes for `mulmod`. There are probably more issues hidden.

IMHO, it should be discussed whether and how portability could be improved:
* We could wrap every `long` typedef into appropriate #ifdef directives for `_WIN32` (or better `__MINGW32__`) and set it to `long long` (I don't think this is a good idea, we might end up in "#ifdef-hell")
* Make use of `<stdint.h>` and use types like `int64_t` instead of `long` (I would vote for that)
* Refer to types defined in `<caml/config.h>`, e.g., `ARCH_INT64_TYPE`. This way, code would be "in-line" with OCaml compiler.

In any case, this is not a 1 day exercise, and careful testing is required. Also, a solution depend on which architectures/compilers are supported in general. Is there a list of actual and planned architectures to be supported?

**Comment by mseri** [comment]
Right now only Linux and MacOS with gcc on x86_64 are "officially" supported in the sense that they are actively used so are being tested thorougly also in applications (@ryanrhymes correct me if I am wrong), but there has been growing interest using owl on ARM64 (Aarch64) which has led to a number of small PR recently to make the build work (tests seem to pass there).

The use of `stdint` seems to be a good idea for me, this should resolve also potential issues on ARM64. Maybe a similar issue could be laying behind https://github.com/owlbarn/owl/issues/462

I personally would like to have it properly multiplatform, targeting windows on x86_64 (and eventually arm).
@ryanrhymes what is your opinion.

**Comment by jzstark** [comment]
Hmm, on my machine executing `mulmod` as above leads to a `Floating point exception: 8` error. I'm investing this problem.

**Comment by kkirstein** [comment]
Maybe a division by zero case (I think, that's the only floating point exception that  might happen during integer arithmetic). Could be also due to overflow of 32/64 bit integers. I've got a fix for my Windows setup ([see this commit](https://github.com/kkirstein/owl/commit/d2f94b800db7f750eee7a20683f4f59cdef597da)), but at the same time found more possible issues with different `long` bit size (that's why I did not send a PR yet).

**Comment by ryanrhymes** [comment]
> Right now only Linux and MacOS with gcc on x86_64 are "officially" supported in the sense that they are actively used so are being tested thorougly also in applications (@ryanrhymes correct me if I am wrong), but there has been growing interest using owl on ARM64 (Aarch64) which has led to a number of small PR recently to make the build work (tests seem to pass there).
> 
> The use of `stdint` seems to be a good idea for me, this should resolve also potential issues on ARM64. Maybe a similar issue could be laying behind #462
> 
> I personally would like to have it properly multiplatform, targeting windows on x86_64 (and eventually arm).
> @ryanrhymes what is your opinion?

Sorry for the late reply, @mseri @kkirstein you both are right ... `long`  is not a good idea. We need to support ARM64 and other platforms in the long run.
