### ISSUE TITLE
Test failure in AD

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#566]
I've submitted a [PR](https://github.com/ocaml/opam-repository/pull/17885) to `opam-repository` to add the OCaml v1.0.1 to opam, but currently the test seems to fail on OCaml 4.11 at the `sylvester` function:

```
# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ [FAIL]        algodiff matrix              0   reverse mode.                 │
# └──────────────────────────────────────────────────────────────────────────────┘
# [failure] 
# failed reverse mode operations
#        sylvester (1/20)
# 
# Logs saved to `~/.opam/4.11/.opam-switch/build/owl.1.0.1/_build/default/test/_build/_tests/Owl/algodiff matrix.000.output'.
#  ──────────────────────────────────────────────────────────────────────────────
# 
# Full test results in `~/.opam/4.11/.opam-switch/build/owl.1.0.1/_build/default/test/_build/_tests/Owl'.
# 1 failure! in 2.000s. 1396 tests run.
```

Also accordingly to [this log](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/bdde2ab326dcf5ecf4a9f53b2aff0a3c12b05f7f/variant/compilers,4.11,owl-base.1.0.1,revdeps,owl.1.0.1,tests), unittest also fails for the `discrete_lyapunov2` function. 

Do we know how to fix this issue?  @tachukao

**Comment by tachukao** [comment]
@jzstark This looks like an error due to the finite difference approximations that we make, as only 1 out of 20 random initialisations failed. Theses tests pass locally for me. Is there a way to trigger the test again with opam? @mseri, any thoughts?

**Comment by ryanrhymes** [comment]
sylvester fails randomly. Does it use randomly generated inputs? If so, one temporary solution is using fixed inputs.

**Comment by tachukao** [comment]
That's a good idea. I just made a PR #567, fixing the random seed for the AD unit tests.

**Comment by mseri** [comment]
Should we close this or we want to keep it open to think about an improvement for the tests?
