### ISSUE TITLE
Potential Lapacke.ptsv issue

### ISSUE THREAD

**Issue by meggermo** [owlbarn/owl#573]
Since Owl is column oriented I expected the following to work:
```
let tridiag n nrhs =
  let d = Mat.init 1 n (fun _ -> 4.0) in
  let e = Mat.init 1 (n-1) (fun _ -> 1.0) in
  let b = Mat.ones nrhs n in
  Owl.Lapacke.ptsv ~d ~e ~b
```
So I expected that b would have to have shape [nrsh, n]. However, when running this code I get the following error:
```
Fatal error: exception "Assert_failure src/owl/lapacke/owl_lapacke.ml:2625:2"
Raised at file "src/owl/lapacke/owl_lapacke.ml", line 2625, characters 2-17
```
Checking the owl_lapacke apparently b has to have shape [n, nrhs]. When I change it the code produces the correct result.

I am not sure if this is a bug, but it is quite inconvenient: 
In my code I compute b from a c-layout matrix (with nrhs = 2) and then I first need to transpose b and then again transpose the result produced from ptsv so I can assign it to my c-layout matrix again. That seems quite inefficient.

**Comment by jzstark** [comment]
Defining this function in the current version of Owl should work fine.
