### ISSUE TITLE
Not using the align-* options of ocamlformat

### ISSUE THREAD

**Issue by gpetiot** [owlbarn/owl#586]
Hi, as the continuous effort of maintaining ocamlformat and simplifying the code and its options, the `align-*` options (`--align-cases`, `--align-constructors-decl`, `--align-variants-decl`) often come up as options we would like to remove from ocamlformat.

Apart from the (ocamlformat) code simplification, and moving slowly but surely towards an uniform configuration that would suit more projects, we can also raise the argument that using such option may add some noise in the reformatting each time one aligned item is added or removed (since they are all reindented when the longest item changes) and that's not something we want to promote in ocamlformat.

Since `owl` is one of the very few projects using these options, what do you think of the possibility of having them removed from ocamlformat in the future?
cc @emillon @julow

**Comment by gpetiot** [comment]
Friendly ping about this, these are options we would like to deprecate then remove for the next release. We strongly feel that this kind of feature should live outside of `ocamlformat` (a postprocessing tool could be written to realign the lines of choice)

**Comment by jzstark** [comment]
@gpetiot Thanks for the advice! Please feel free to make or amend the current PR, and we will merge it once v0.20.0 is released.
