### ISSUE TITLE
Maths.combination n m returns 0 when m is 0 or n

### ISSUE THREAD

**Issue by gitogito** [owlbarn/owl#587]
`Maths.combination n 0` must returns 1 instead of 0.
`Maths.combination n n` must returns 1 instead of 0.

**Comment by kafka64** [comment]
nCn and nC0 can be fixed by simply changing the return value from 0. to 1. in owl_maths_special_gamma.c but now I'm curious if Maths.combination should be throwing exception for the 0Cn or any cases where m > n (fact_table[n-m] would be undefined).

**Comment by mseri** [comment]
IMO it should fail
