### ISSUE TITLE
Mat.flatten does not return a Mat.mat

### ISSUE THREAD

**Issue by jfeser** [owlbarn/owl#596]
Mat.flatten returns a one-dimensional ndarray, so using Mat operations on it fails with a "wrong number of indices" error.

**Comment by tachukao** [comment]
Hi @jfeser , I think the idea of `flatten` is to mimic [`numpy.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html), which returns a 1D ndarray. 

Implementation-wise, `flatten` is just a simple wrapper around. Maybe you can try `Mat.(reshape x [|1; numel x|])`? Would that be acceptable?
