### ISSUE TITLE
Not able to install natively on Apple M1

### ISSUE THREAD

**Issue by ddph3dg** [owlbarn/owl#597]
I'm just trying Owl and couldn't get this to compile natively on a M1 Mac.
If you use the rosetta emulation on the Mac you can get a working system.

I used:
sudo arch -x86_64 before the rest of the "opam/master/shell/install.sh" command. Then opam just works for the full owl install. The other awkward thing is to put arch -x86_64 before all the brew installs eg plplot openblas etc.

**Comment by rizo** [comment]
To add some extra detail, compiling owl for ARM fails with:

```
# gcc: error: unrecognized command-line option '-msse2'
# [...]
# (cd _build/default/src/owl && /usr/bin/gcc -no-pie -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -D_FILE_OFFSET_BITS=64 -no-pie -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -g -O3 -Ofast -march=native -mfpmath=sse -funroll-loops -ffast-math -DSFMT_MEXP=19937 -msse2 -fno-strict-aliasing -Wno-tautological-constant-out-of-range-compare -Wno-logical-op-parentheses -g -I /app/_opam/lib/ocaml [...]
# gcc: error: unrecognized command-line option '-mfpmath=sse'
# gcc: error: unrecognized command-line option '-msse2'
#          gcc src/owl/zeta.o (exit 1)
```

**Comment by mseri** [comment]
You can use owl flags to disable those, or pin https://github.com/owlbarn/owl/pull/570
This is not enough to compile for M1 though

**Comment by jhgorse** [comment]
Others have this issue as well:
https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1

It appears to be resolved in clang 13.0 with:
```
-mcpu=apple-m1
```

**Comment by ddph3dg** [comment]
I managed to get Eigen lib working by setting EIGEN_FLAGS with the -mcpu=apple-m1 as mentioned above. I also set OWL_FLAGS the same way. However in the aeos dune specification there is no way to override the aeos_c_flags.sexp settings which still have 
-march=native.

**Comment by jhgorse** [comment]
@ddph3dg 
I use these variables which can get you past the AEOS using `make`:
```
export OWL_CFLAGS="-g -O3 -Ofast -mcpu=apple-m1 -funroll-loops -ffast-math -DSFMT_MEXP=19937 -fno-strict-aliasing -Wno-tautological-constant-out-of-range-compare -DOWL_ARCH_x86_64=0 -DOWL_ARCH_i386=0"; export OWL_AEOS_CFLAGS="-g -O3 -Ofast -mcpu=apple-m1 -funroll-loops -ffast-math -DSFMT_MEXP=19937 -fno-strict-aliasing -DOWL_ARCH_x86_64=0 -DOWL_ARCH_i386=0"
make
```

**Comment by ddph3dg** [comment]
I get past AEOS as you say using these settings. The next error is about is about OWL_ARCH_x86_64 & i386, so it looks like setting this to 0 is ignored in the following:
src/owl/core/owl_core_utils.c:255:3: error: invalid output constraint '=a' in asm
# [...]
#   ^
# src/owl/core/owl_macros.h:97:36: note: expanded from macro 'CPUID'
#     __asm__ __volatile__ ("cpuid": "=a" (cpuinfo[0]), "=b" (cpuinfo[1]), "=c" (cpuinfo[2]), "=d" (cpuinfo[3]) : "0" (func), "2" (id) );
#                                    ^
# src/owl/core/owl_core_utils.c:277:5: error: invalid output constraint '=a' in asm
#     CPUID(cpuinfo, 0x0, 0);

**Comment by jhgorse** [comment]
@ddph3dg yes, that is briefly captured in the #570 thread. I removed the intel/amd cache detection code because the compiler does not know whether or not to include those symbols, so it dies when it tries to turn those functions into object code. My latest hacking progress can be seen or cloned from here (branch mseri-patch-1):
https://github.com/jhgorse/owl/tree/mseri-patch-1

After that you can expect to fail on the implicit linking to libgcc_s from OpenBLAS.

**Comment by ddph3dg** [comment]
@jhgorse OK, I may try that later, but for the moment the Rosetta intel emulation works amazingly well considering what must be going on under the hood. I haven't timed anything to do with BLAS as that wasn't possible but plain ocaml seems to run at about 80% of the speed of the native implementation, and that is more than adequate to play around with the system.

**Comment by jhgorse** [comment]
@ddph3dg could you document the Rosetta emulations steps in a bit more detail? I've failed a couple of tries at it.

**Comment by ddph3dg** [comment]
From a clean system with no homebrew  and opam and I also had a full Xcode + command line utilities:
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
arch -x86_64 brew install plplot zlib openblas opam
export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"
# looks like opam doesn't need arch -x86_64 as it was installed as an intel binary
opam init   # answer y for all
opam install core utop
opam install async yojson core_extended core_bench cohttp async_graphics cryptokit menhir
opam owl owl-top
eval $(opam env)

**Comment by jhgorse** [comment]
Nit: 2nd to last line should be `opam install owl owl-top`

XQuartz? Intense dependencies. It might make sense to pull in something like https://github.com/ocornut/imgui instead.

I died on the last opam install of owl and owl-top:
```
⬇ retrieved eigen.0.3.0  (cached)
[ERROR] The compilation of conf-openblas.0.2.1 failed at "sh -exc cc $CFLAGS $(pkg-config --cflags openblas) test.c $(pkg-config
        --libs openblas)".
[ERROR] The compilation of owl-base.1.0.1 failed at "dune build -p owl-base -j 9".
[ERROR] The compilation of eigen.0.3.0 failed at "dune build -p eigen -j 9".
```
Looks like assembly mnemonic issues and OpenBLAS not getting found, even though it exists at PKG_CONFIG_PATH.

My starting conditions were not clean. I used a separate arch homebrew install. Though, for reference:
```
sudo mkdir -p /usr/local/homebrew
sudo chown `id -u`:`id -g` /usr/local/homebrew
cd /usr/local
git clone https://github.com/Homebrew/brew homebrew
# use the /usr/local/homebrew/bin/brew for this install
arch -x86_64 /usr/local/homebrew/bin/brew install plplot zlib openblas opam
export PKG_CONFIG_PATH="/usr/local/homebrew/opt/openblas/lib/"
opam init   # answer f,y for all rest, made a .zshrc in /usr/local/homebrew
opam install core utop
opam install async yojson core_extended core_bench cohttp async_graphics cryptokit menhir
opam owl owl-top  # breaks here
eval $(opam env)
```

**Comment by ddph3dg** [comment]
My mistake on the second last line. 
Also I have XQuartz installed outside homebrew, but in the past I remember opam pulled it in as a dependency  using the "local" package manager without any issues. Here is my printenv so you can compare the environmental variables I set to see if any jump out at you:
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
PKG_CONFIG_PATH=/usr/local/opt/openblas/lib/pkgconfig
LANG=en_US.UTF-8
LC_CTYPE=UTF-8

**Comment by mseri** [comment]
On macos with macports I am able to compile and use owl.
The changes are in github.com/mseri/owl#arm64 and github.com/mseri/eigen#arm64

It is not good for production: eigen has some linking issues so some tests are still failing. But I can run a lot of my non-machine-learning code on MacOS ARM M1

**Comment by jhgorse** [comment]
@mseri I confirm that your owl/arm64 builds and tests on mac m1.
```
git clone https://github.com/mseri/owl/ -b arm64 owl_mseri
opam pin owl owl_mseri
cd owl_mseri && make test
```

All tests pass.

- [ ]

**Comment by mseri** [comment]
Actually there is one more step required (for now) to fix an issue in homebrew: https://github.com/owlbarn/owl/issues/611#issuecomment-1120238578

I will Update my branches or open a new PR once they are merged in order to fix it for once
