### ISSUE TITLE
LAPACKE problems

### ISSUE THREAD

**Issue by emiruz** [owlbarn/owl#614]
I'm on Debian. I have OpenBLAS installed. I've tried installing owl. From utop:
```
#require "owl";;

Cannot load required shared library dllowl_stubs.
Reason: ./dllowl_stubs.so: ./dllowl_stubs.so: undefined symbol: LAPACKE_dtpmqrt.
```
Whilst owl-base loads ok, I get the following output for owl-plplot and owl-top:

```
#require "owl-top";;

No such package: owl-top
```
Help!

**Comment by emiruz** [comment]
I fixed this by uninstalling owl and then reinstalling it with:
```
opam pin add owl --dev-repo -v
```
Meanwhile none of owl-top owl-plplot and owl-zoo were installed with owl and needed to be installed separately. I used the same syntax as above to install them. attempt to install owl-top using opam install owl-top lead to a "no solution" error message.

**Comment by mseri** [comment]
Only the master branch currently support 4.14. I hope a new release can be done soon and that it will include #609
