### ISSUE TITLE
The setter function for matrices in Owl_algodiff.D.Mat does not work

### ISSUE THREAD

**Issue by LongPham7** [owlbarn/owl#629]
The `set` function from `Owl_algodiff.D.Mat` does not work properly. Consider the following code in the top level (i.e. OCaml's REPL):
```ocaml
#require "owl";;
open Owl_algodiff.D;;
let x = Mat.ones 1 3;;
Mat.get x 0 0;; 
Mat.set x 0 0 (pack_elt 42.);;
Mat.get x 0 0;;
```
The first occurrence of `Mat.get x 0 0` returns 1 (more precisely, 1 inside a wrapper), as expected. But the second occurrence of `Mat.get x 0 0` also returns 1, even though I ran `Mat.set x 0 0 (pack_elt 42.)` before calling `Mat.get x 0 0` the second time. Do I use `Mat.set` correctly? Thanks in advance!

**Comment by jzstark** [comment]
The `set` operator in `Algodiff` module works different from that in the normal `Ndarray` module. Both versions of code below are true:
```ocaml
#require "owl";;
open Dense;;
let x = Mat.ones 1 3;;
Mat.get x 0 0;; 
Mat.set x 0 0 42.;;
Mat.get x 0 0;;
```
or

```ocaml
#require "owl";;
open Owl_algodiff.D;;
let x = Mat.ones 1 3;;
Mat.get x 0 0;; 
let y = Mat.set x 0 0 (pack_elt 42.);;
Mat.get y 0 0;;
```

**Comment by LongPham7** [comment]
@jzstark Thanks a lot for getting back to me!
