### ISSUE TITLE
Cannot install owl-1.1 through opam because of `unmet availability conditions`

### ISSUE THREAD

**Issue by hexclover** [owlbarn/owl#634]
```console
$ opam install owl.1.1         
[ERROR] owl = 1.1 unmet availability conditions: 'arch = "x86_32" | arch = "x86_34"'
```

I guess that `x86_34` was a typo? See https://github.com/ocaml/opam-repository/commit/2b95c7a9f155c55a088377cee301c20e157b3176

**Comment by jzstark** [comment]
Thanks a lot for reporting this. Indeed that looks like a typo of `x86_64`.  Any suggestion about how should we fix this issue @mseri ?

**Comment by mseri** [comment]
Fixed upstream in https://github.com/ocaml/opam-repository/pull/23461/commits/ca10502ff498ba11f4eddea2354778dc7e1fa241

will be propagated to the opam index in 1-2h
