### ISSUE TITLE
Incorrect `Owl_const.min_float64` value?

### ISSUE THREAD

**Issue by patricoferris** [owlbarn/owl#638]
Hello

I was trying to find some minimum and maximum values using `Owl_base_dense_ndarray_d` and I think the value used for `Owl_const.min_float64` which is `Stdlib.min_float` might not be right. The `Stdlib.min_float` is "The smallest **positive**, non-zero, non-denormalized value of type float". I know floating-point numbers are a little strange so perhaps I'm mistaken/doing something wrong?

```ocaml
# let arr = Owl_base_dense_ndarray_d.of_array [| -1.; -2. |] [| 2 |];;
# Owl_base_dense_ndarray_d.(get (max ~keep_dims:false arr) [| 0 |]);;
- : float = 2.22507385850720138e-308
```

**Comment by jzstark** [comment]
I execute `Stdlib.min_float` and the returned result is exactly the same representation using scientific notation, which is indeed a very small and positive float value.
