### ISSUE TITLE
Broken link to Algodiff module.

### ISSUE THREAD

**Issue by gl-yziquel** [owlbarn/owl#648]
The link to Algodiff module on https://www.cl.cam.ac.uk/~lw525/owl/chapter/operator.html is broken.

It leads here https://github.com/owlbarn/owl/blob/main/src/owl/optimise/owl_algodiff_generic.ml i.e. nowhere.

**Comment by ChickenWhisky** [comment]
Hi is this the right link to the required module?
https://github.com/owlbarn/owl/blob/ab3aeb97cc25ba5bae125add82b069227ee3af65/src/owl/algodiff/owl_algodiff_primal_ops.ml

**Comment by jzstark** [comment]
Thanks for pointing it out. The mentioned doc is not actively maintained now. The `algodiff` code is currently positioned at: https://github.com/owlbarn/owl/tree/main/src/base/algodiff .
