### ISSUE TITLE
`Dataframe.to_cols` returns columns of incorrect size

### ISSUE THREAD

**Issue by ivg** [owlbarn/owl#654]
The function returns an array of series with an incorrect size, i.e., `get_col m i <> (to_columns m).(i)`. Unlike `get_col`, which extracts a subarray of proper size, the `to_columns` function is returning the raw containers with the size equal to capacity.

P.S. I can PR a  fix, but I am not sure if this repository is alive and if it would ever be merged, ping me if you're interested.

**Comment by mseri** [comment]
I cannot speak for the repository but I do periodically merge fixes from PRs in my local repo, so if you take the time to do it there will surely be people that benefit from it :)
