### ISSUE TITLE
Reintroduce owl-plplot

### ISSUE THREAD

**Issue by mseri** [owlbarn/owl#659]
`owl-plplot` provided a convenient and seamless way to plot, and is also used in the documentation. It is such thin layer and so easily installable that it is a pity that it has been removed.

**Comment by jzstark** [comment]
The plplot module itself is a thin layer, but it depends on the plplot library which is a bit heavy. The previous idea is to reduce external reliance such as eigen and plplot. Perhaps we can follow the `numpy+matplotlib` paradigm and put the plplot stuff in a separate repo in owlbarn.

**Comment by mseri** [comment]
I understand removing eigen since the way it needs to be compiled to work properly is simply a nightmare. Similarly I understand that removing aeos simplifies the code.

But ocaml-plplot is a rather stable and well designed package, and owl-plplot has always worked fine on all systems so far, so in principle you could keep it there at no extra cost.

in any case, I thunk the location does not matter. It is perfectly fine on a separate repository if you prefer it that way. Without owl-plplot there is no owl ergonomic plotting solution at the moment so it would be nice not to lose it

**Comment by jzstark** [comment]
True, I totally agree that plotting is an important part in numerical computing, just like `NumPy` is accompanied by `Matplotlib`.  I've added it to the Todo list in the Project. It would be great if any one interested can help to add this package.

**Comment by mseri** [comment]
If you create an empty owl-plplot repository and give me (also just temporary) writing rights, I can push my fork (which is just a copy of the old sources) there

**Comment by jzstark** [comment]
Hi Marcello, I've created the repo and a temp write access as suggested.
Thanks a lot for helping to set it up!

**Comment by mseri** [comment]
Done
