### ISSUE TITLE
Moore-Penrose pseudoinverse

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#77]
I don't know how useful it would be in general to have this function available.  At present my only use for it is that I'd like to experiment with a Moore-Penrose pseudoinverse to help me understand its role in a proof I'm reading.  Presumably there are more serious use cases.  I thought I would record the absence of the function as an issue, but can't claim any urgency for implementing it.  (As for my need to experiment, I think Matlab has the function, and I can learn enough Matlab to experiment with it if necessary.)

**Comment by ryanrhymes** [comment]
Moore-Penrose pseudoinverse can be implemented with `svd`. I have added `pinv` function to `Linalg` module. You can call from `S/D/C/Z` modules depending on the number types. Let me know if you find any bugs.

**Comment by mars0i** [comment]
Thanks very much.  I appreciate this a lot.  I had started working on an implementation of `pinv` using `svd` but I didn't really know what I was doing--was just trying to follow information I found on the web.  I'm not sure it was working right, and apparently one has to make a decision about how small a number is to treat it as zero.  I wasn't sure what to do about that.  I just looked at your version, and I don't understand everything, but it looks like it deals with other issues I didn't know about.  It will be very nice to be able to use the Moore-Penrose inverse in OCaml.  There were other ways I had to experiment with it, but they were awkward.

**Comment by mars0i** [comment]
Just checking: I understand that the very small numbers in the matrices below are effectively zero, and I should expect that they would not have been turned into zeros, right?  This behavior is what is  intended, correct?  I see that there's a place in the implementation that maps small numbers to zeros, but I guess you can still end up with non-zero zeros (so to speak) in the end result.
```
# module M = Owl.Mat;;
module M = Owl.Mat
# module L = Owl.Linalg.Generic;;
module L = Owl.Linalg.Generic
# let m = M.sequential 2 8;;

   C0 C1 C2 C3 C4 C5 C6 C7
R0  0  1  2  3  4  5  6  7
R1  8  9 10 11 12 13 14 15

val m : M.mat =
# let m' = L.pinv m;;

           C0           C1
R0  -0.135417    0.0520833
R1   -0.10119    0.0416667
R2 -0.0669643      0.03125
R3 -0.0327381    0.0208333
R4  0.0014881    0.0104167
R5  0.0357143 -6.93889E-18
R6  0.0699405   -0.0104167
R7   0.104167   -0.0208333

val m' : (float, Bigarray.float64_elt) L.t =
# M.(m *@ m' *@ m);;

            C0 C1 C2 C3 C4 C5 C6 C7
R0 -1.9984E-15  1  2  3  4  5  6  7
R1           8  9 10 11 12 13 14 15

- : (float, Bigarray.float64_elt) M.op_t2 =
# M.(m' *@ m *@ m');;

           C0           C1
R0  -0.135417    0.0520833
R1   -0.10119    0.0416667
R2 -0.0669643      0.03125
R3 -0.0327381    0.0208333
R4  0.0014881    0.0104167
R5  0.0357143 -1.56125E-17
R6  0.0699405   -0.0104167
R7   0.104167   -0.0208333

- : (float, Bigarray.float64_elt) M.op_t2 =
```

**Comment by ghennequin** [comment]
just wanted to add that I use `pinv` often in my work; thanks for having added this

**Comment by ryanrhymes** [comment]
@mars0i apologies for the late reply, I lost track of this issue. Yes, there is small numerical difference. You can use a `map` function to zero them out. I do not know if Scipy, Julia, or Matlab has any specific function to fix a value around certain range ... if you know, please suggest.

Although this can be achieved by `map` function, I think a specialised function would be more efficient.

**Comment by mars0i** [comment]
No problem at all.  I don't have much experience with Matlab, and none with Scipy or Julia, though.  I like the idea of a specialized function.  Maybe `pinv` is a little bit of a special case because precise zeros as opposed to small numbers are theoretically what should be returned for certain elements; they have a special meaning.  However, `Owl.Dense.Matrix.Generic.approx_equal` and the other related functions there might be all that one needs in practice.
