### ISSUE TITLE
Control rounding in matrix printing?

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#82]
Hi, is there a way to control the rounding of floats in the printing of matrices?  Here's  an illustration:
```OCaml
# b1, b2;;

     C0   C1
R0 0.45 0.55
R1 0.35 0.65


     C0   C1
R0 0.45 0.55
R1 0.35 0.65

- : M.mat * M.mat = (, )
# Mat.(b1 - b2);;

             C0 C1
R0 -5.55112E-17  0
R1            0  0

- : (float, Bigarray.float64_elt) M.op_t2 =

# Mat.get b1 0 0, Mat.get b2 0 0;;
- : float * float = (0.449999999999999956, 0.45)
```
In most circumstances, I do like the fact that for example 0.449999999999999956 prints as 0.45, but not always.  In this case the two matrices were generated by code that's supposed to remove identical matrices, so when two matrices look the same, it's surprising, and I have to go through extra steps to figure out how they differ.  (I have an optional parameter in the code that will round to *n* decimal places, but in this case I didn't use it and I wondered if I had a bug.)  

At this point is there a public variable that can be used to control the print rounding behavior?  (I took a look at owl_pretty.ml* but didn't notice anything like this.  That doesn't mean it's not there. :-)

It's possible that this should be combined with #32 .

**Comment by ryanrhymes** [comment]
@mars0i it took a while, my apologies for this. With the brand new pretty printing module, you can do this now. What you need to do is just passing in a `fmt` function to convert an element to into string.

```ocaml
let x = Mat.uniform 4 4;;
let fmt = Printf.sprintf "%.3f";;
Mat.print ~fmt x;;
```

Please refer to https://github.com/ryanrhymes/owl/blob/92e30acd425a3833b4c3301772b1ca31de915fa4/src/owl/owl_dense_ndarray_generic.mli#L693

**Comment by mars0i** [comment]
That's great.  Thanks Liang.  This is more general than what I had in mind, but seems easy to use.
